GuildDaily command slash command
DraftBot-A-Discord-Adventure/DraftBot pull request #1069
Opened 2022-04-05 22:57 UTC by romain22222

2022-04-07 21:04 UTC, BastLast requested changes

2022-04-07 21:04 UTC, BastLast commented on src/commands/guild/GuildDailyCommand.ts
> +async function genericAwardingFunction(members: Entity[], awardingFunctionForAMember: (member: Entity) => Promise<void> | void) {
J'aimerai de la doc sur les fonctions comme ca qui sont pas forcément évidentes

2022-04-07 22:39 UTC, romain22222 commented
- transformer les data dans la commande gd en constantes et le virer du type

2022-04-08 07:13 UTC, romain22222 commented on src/commands/guild/GuildDailyCommand.ts
> +		if (await BlockingUtils.getPlayerBlockingReason(member.discordUserId) === "fight") {
présent à beaucoup d'endroits dans le bot, je crée l'issue en correspondance et faudra changer ca

2022-04-08 20:36 UTC, BastLast approved these changes

2022-04-08 20:36 UTC, merged