Fightcommandtoslashcommmand
DraftBot-A-Discord-Adventure/DraftBot pull request #1093
Opened 2022-04-18 17:19 UTC by BastLast

2022-04-26 09:41 UTC, BastLast commented
@niqore  faudrait qu'on se cale une session de travail là dessus asap

2022-06-19 20:32 UTC, romain22222 requested changes

2022-06-19 20:32 UTC, romain22222 commented on src/commands/player/FightCommand.ts
> +		disallowEffects: [Constants.EFFECT.BABY, Constants.EFFECT.DEAD],
Euhhhhh je crois qu'il y a un problème sur les effets, devrait y avoir que smiley qui serait auto

2022-06-19 20:32 UTC, romain22222 commented on src/core/fights/FighterStatus.ts
> +	LOSER	,
pourquoi mettre autant d'espace

2022-06-19 20:35 UTC, BastLast commented on src/commands/player/FightCommand.ts
> +		disallowEffects: [Constants.EFFECT.BABY, Constants.EFFECT.DEAD],
c'est géré dans le canfight parce que pour les friendly faut pas bloquer :)

2022-06-19 20:35 UTC, romain22222 approved these changes

2022-06-19 20:37 UTC, merged