Test for codesceane analysis #1073
DraftBot-A-Discord-Adventure/DraftBot pull request #1163
Opened 2022-06-24 19:56 UTC by Pietagorh

2022-06-24 22:39 UTC, romain22222 requested changes

2022-06-24 22:39 UTC, romain22222 commented on src/commands/admin/SendLogsCommand.ts
> +			sendErrorMessage(interaction.user, interaction, language, sendLogsModule.get("noLogFile"));
reply ?

2022-06-24 22:39 UTC, romain22222 commented on src/commands/guild/GuildShopCommand.ts
> +function getFoodShopItem(guildShopTranslations: TranslationModule, name: string, language: string, amounts: number[], interaction: CommandInteraction) {
coucou pieta, le bot a raison, fais moi descendre ce nombre à 4, YOU CAN DO THIS

2022-06-24 22:39 UTC, romain22222 commented on src/core/utils/BlockingUtils.ts
>  	return false;
faut refaire la fonction, grosse duplication et nesting de ifs (c'est du au refactor de replyErrorMessage)

2022-06-24 22:39 UTC, romain22222 commented on src/core/messages/DraftBotBroadcastValidationMessage.ts
> +			sendErrorMessage(this._interaction.user, this._interaction, this._language, this._translationModule.errorBroadcastCancelled, true);
boarf, ici garde user tout court, c'est le même
```suggestion
			sendErrorMessage(user, this._interaction, this._language, this._translationModule.errorBroadcastCancelled, true);
```

2022-06-24 22:39 UTC, romain22222 commented on src/core/messages/DraftBotBroadcastValidationMessage.ts
> +		// eslint-disable-next-line max-len
👀

2022-06-24 22:39 UTC, romain22222 commented on src/core/messages/DraftBotBroadcastValidationMessage.ts
> +		sendErrorMessage(this._interaction.user, this._interaction, this._language, format(this._translationModule.errorOtherDeny, {pseudo: (await Entities.getByDiscordUserId(user.id)).getMention()}));
si tu as une ligne trop grosse, saute des lignes entre les paramètres d'une fonction, ca va déjà bien aider, ensuite saute des lignes pour les objets entre crochets, comme dans un json

2022-06-24 22:39 UTC, romain22222 commented on src/core/messages/DraftBotBroadcastValidationMessage.ts
> +				sendErrorMessage(this._interaction.user, this._interaction, this._language, this._translationModule.errorSelfAccept);
```suggestion
				sendErrorMessage(user, this._interaction, this._language, this._translationModule.errorSelfAccept);
```

2022-06-24 22:39 UTC, romain22222 commented on src/core/messages/DraftBotBroadcastValidationMessage.ts
> +			sendErrorMessage(this._interaction.user, this._interaction, this._language, this._translationModule.errorSelfAcceptSpam);
```suggestion
			sendErrorMessage(user, this._interaction, this._language, this._translationModule.errorSelfAcceptSpam);
```

2022-06-24 22:39 UTC, romain22222 commented on src/core/messages/DraftBotErrorEmbed.ts
> +	constructor(user: User, interaction: CommandInteraction, language: string, reason: string, isCancelling = false) {
mwais, la ca va être dur de faire descendre le nombre de params à 4

Mon idée (pas pour tout de suite, mais faudra y penser) faire un embed spécial pour le cancelling (en gros, on fait un embed qui étend celui ci, le constructeur c'est super(<les paramètes de celui ci>) avec un this.formatAuthor qui viendra réécrire l'ancien. par définition ce seront les mêmes embeds en terme de style, ils seront juste créés de facon différente niveau code

2022-06-24 22:39 UTC, romain22222 commented on src/core/messages/DraftBotShopMessage.ts
>  import {DraftBotReaction} from "./DraftBotReaction";
t'as revérifié l'exécution du shop dans sa globalité, j'ai un mauvais préssentiment

2022-06-24 22:39 UTC, romain22222 commented on src/core/utils/ErrorUtils.ts
> +	});
du coup, même remarque que pour drafterrorembed, faudrait faire (dans le futur) une fonction qui permet d'envoyer un cancel

2022-06-25 07:57 UTC, Pietagorh commented on src/core/messages/DraftBotBroadcastValidationMessage.ts
> +		// eslint-disable-next-line max-len
Y'a juste un caractère en trop ça vaaa

2022-06-25 07:59 UTC, romain22222 commented on src/core/messages/DraftBotBroadcastValidationMessage.ts
> +		// eslint-disable-next-line max-len
les disables sont à utiliser qu'en cas d'urgence et qu'il n'est pas possible de faire autrement, ce qui n'est pas le cas ici

2022-06-25 08:00 UTC, BastLast commented
Nan, Romain a raison, ceci est illégal. 
Merci de rajouter un retour à la ligne et de ne pemas utiliser eslint disable

Sam 25 juin 2022, à 09:57, Pietagorh a écrit :
> 
> 
> ***@***.**** commented on this pull request.
> 
> 
> In src/core/messages/DraftBotBroadcastValidationMessage.ts <https://github.com/DraftBot-A-Discord-Adventure/DraftBot/pull/1163#discussion_r906651203>:
> 
> >  			BlockingUtils.unblockPlayer(user.id, this._blockingReason);
>  			return true;
>  		}
>  		if (this._spammers.includes(user.id)) {
>  			return false;
>  		}
>  		this._spammers.push(user.id);
> -		await sendErrorMessage(user, this._interaction.channel, this._language, format(this._translationModule.errorOtherDeny, {pseudo: (await Entities.getByDiscordUserId(user.id)).getMention()}));
> +		// eslint-disable-next-line max-len
> 
> Y'a juste un caractère en trop ça vaaa
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/DraftBot-A-Discord-Adventure/DraftBot/pull/1163#discussion_r906651203>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AJCVYAUS5BTALKNN3G3EEFDVQ23YPANCNFSM5ZY25KUA>.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
>

2022-06-25 08:23 UTC, Pietagorh commented on src/core/messages/DraftBotShopMessage.ts
>  import {DraftBotReaction} from "./DraftBotReaction";
Il marche parfaitement

2022-06-25 12:07 UTC, romain22222 approved these changes

2022-06-25 12:07 UTC, romain22222 commented on src/core/utils/BlockingUtils.ts
> +		}));
```suggestion
		replyErrorMessage(
			interaction,
			language,
			Translations.getModule("error", language).format(
				user === interaction.user ? "playerBlocked" : "anotherPlayerBlocker", {
					context: getErrorReasons(blockingReason, language),
					username: escapeUsername(user.username)
				}
			)
		);
```

2022-06-25 12:07 UTC, romain22222 commented on src/core/utils/BlockingUtils.ts
> +		}));
(je propose cette modif car les deux constantes que tu crées sont utilisés une seule fois, autant directement les mettre en paramètre

2022-06-25 12:07 UTC, romain22222 commented on src/core/utils/ErrorUtils.ts
> +	});
#1165

2022-06-25 12:15 UTC, merged