fix #1514
DraftBot-A-Discord-Adventure/DraftBot pull request #1529
Opened 2022-10-21 20:34 UTC by BastLast

2022-10-21 21:00 UTC, romain22222 commented on src/core/database/game/models/Player.ts
> +
petite duplication de code la, le seul truc différent sur les deux fonctions c'est le score / weeklyscore

2022-10-21 21:34 UTC, BastLast commented on src/core/database/game/models/Player.ts
> +
Moui mais c'est plus modulaire :)

2022-10-21 21:34 UTC, BastLast commented on src/core/database/game/models/Player.ts
> +
Et plz ça fait 2 lignes

2022-10-21 21:36 UTC, romain22222 commented on src/core/database/game/models/Player.ts
> +
OSEF TU ME REPING SANS VERIF, TU LE FAIS CE REFACTOR

2022-10-22 08:41 UTC, Pietagorh approved these changes

2022-10-22 08:42 UTC, merged

2022-10-22 08:43 UTC, romain22222 requested changes

2022-10-22 08:43 UTC, romain22222 commented on src/core/database/game/models/Player.ts
> +
2 choses : 
- 1 pourquoi ne pas directement appeler la fonction à l'endroit approprié au lieu de passer par une fonction tierce qui ne sert à rien
- 2 y'a 3 moyen de rank, mais seul deux versions sont utilisés, où est la 3e
-

2022-10-22 08:45 UTC, BastLast commented on src/core/database/game/models/Player.ts
> +
- Parce que plus lisible dans le code directement imo et + souple pr dans le futur mais j'accorde que ça peut se débattre
- Parce que j'ai mit la 3ème juste par futur proofin idem ça se débat