Cleaning constants #1432
DraftBot-A-Discord-Adventure/DraftBot pull request #1603
Opened 2022-11-12 18:20 UTC by Pietagorh

2022-11-12 18:51 UTC, romain22222 requested changes

2022-11-12 18:51 UTC, romain22222 commented on src/commands/guild/GuildShopCommand.ts
> +			const xpToAdd = calculateAmountOfXPToAdd(parseInt(guildShopTranslations.get("guildXp.price")));
pourquoi le prix est dans les traductions du shop ?

2022-11-12 18:51 UTC, romain22222 commented on src/core/database/game/models/Player.ts
>  		if (this.level === Constants.FIGHT.REQUIRED_LEVEL) {
si vous êtes parti pour clean les constantes, pourquoi pas le faire sur celles de fight aussi ?

2022-11-12 18:51 UTC, romain22222 commented on src/core/smallEvents/petSmallEvent.ts
> +		amount = RandomUtils.rangedInt(SmallEventConstants.PET.LOVE_POINTS);
codescenes gueule

2022-11-12 18:51 UTC, romain22222 commented on src/core/smallEvents/ultimateFoodMerchantSmallEvent.ts
> +	);
codescenes gueule

2022-11-12 18:52 UTC, Pietagorh commented on src/commands/guild/GuildShopCommand.ts
> +			const xpToAdd = calculateAmountOfXPToAdd(parseInt(guildShopTranslations.get("guildXp.price")));
Parce que tout y est

2022-11-12 18:53 UTC, romain22222 commented on src/commands/guild/GuildShopCommand.ts
> +			const xpToAdd = calculateAmountOfXPToAdd(parseInt(guildShopTranslations.get("guildXp.price")));
oh gosh, vu que ce sont les items du gs, y'a pas moyen de passer ca en constantes bien rangées et tout ?

2022-11-12 23:49 UTC, BastLast commented
@romain22222  @Pietagorh  possible de savoir si c'est fini ?

2022-11-13 00:10 UTC, Pietagorh commented
Ça l'est

2022-11-14 08:16 UTC, BastLast commented
@romain22222  pr info j'attend ta validation pour pouvoir merge ça

2022-11-14 08:21 UTC, romain22222 commented
tjrs pas validé btw :stress:

2022-11-14 09:53 UTC, BastLast commented
@romain22222  @Pietagorh  possible de faire une liste de ce qui manque ?

2022-11-14 10:08 UTC, Pietagorh commented
Romain veut que je refact le guildshpp en même temps
Qu'il le fasse lui-même

2022-11-14 10:10 UTC, BastLast commented
Je propose de le faore dans une nouvelle issue tho

2022-11-14 10:10 UTC, BastLast commented
@romain22222 ça te va ?

2022-11-15 09:27 UTC, BastLast commented
@romain22222 maintenant que l'issue a été créée pour le truc qui a pas été fait, est-ce que tu peux review ?

2022-11-15 09:32 UTC, romain22222 approved these changes

2022-11-15 11:07 UTC, merged