Add notifications #1614
DraftBot-A-Discord-Adventure/DraftBot pull request #1625
Opened 2022-11-19 16:59 UTC by voltou91

2022-11-23 21:52 UTC, Feiryn commented on resources/text/commands/notifications.json
> +				"none": "\uD83D\uDEAB Désactiver les notifications "
Un espace inutile à la fin

2022-11-23 21:52 UTC, Feiryn commented on resources/text/commands/notifications.json
> +			"channelNotification": "Ce message vous est envoyé via le système de notification. Si vous souhaitez que le bot ne vous envoie plus de messages, utilisez la commande /notifications.",
Faudrait mettre le {command:notifications}

2022-11-23 21:54 UTC, Feiryn commented on resources/text/commands/notifications.json
> +			"description": "You select the mode {mode}.",
selected non ?

2022-11-23 21:55 UTC, Feiryn commented on resources/text/commands/notifications.json
> +			"error": "You have closed your DMs !",
enlever le have ? bizarre d'utiliser du present perfect ici

2022-11-23 21:58 UTC, Feiryn commented on src/commands/admin/ChangeGuildChiefCommand.ts
> +					.formatAuthor(tr.get("DM.title"),await draftBotClient.users.fetch(member.discordUserId.toString()))
un espace devant le await

2022-11-23 22:03 UTC, Feiryn commented on src/commands/player/NotificationsCommand.ts
> +	case NotificationsConstants.CHANNEL_SCOPE:
Moi je mets un tab de plus pour les cases, je sais pas vous

2022-11-23 22:04 UTC, Feiryn commented on src/commands/player/NotificationsCommand.ts
> +			{mode: interaction.options.get("mode").value}
Faudrait mettre interaction.options.get("mode").value dans une variable pour pas refaire cette opération pour rien

2022-11-23 22:06 UTC, Feiryn commented on src/core/database/game/migrations/004-edit-notifications.ts
> +	await context.changeColumn("players","dmNotification", DataTypes.STRING);
Dans ce fichier y a plein de formattage à refaire

2022-11-23 22:08 UTC, Feiryn commented on src/core/database/game/models/Player.ts
> +	private async checkChannelAccess(user: User, embed: DraftBotEmbed, language: string): Promise<void> {
Je pense que ce serait mieux de mettre cette fonction et la suivante dans l'utils des messages

2022-11-23 22:09 UTC, Feiryn commented
Faut tester le sharding pour les channels

2022-11-24 23:00 UTC, voltou91 commented on src/commands/player/NotificationsCommand.ts
> +	case NotificationsConstants.CHANNEL_SCOPE:
La raison de pourquoi j'ai pas mit de tab c'est que webStorm me gueule dessus. Puis je viens de regarder et la majorité des switch/case sont comme moi. 
![image](https://user-images.githubusercontent.com/62652451/203872326-d9aab330-3232-4c47-8864-506441d2ed47.png)

2022-11-24 23:27 UTC, voltou91 commented
Manque juste le fait que ça fasse changer le mode de notifications du joueur. Mais pour l'instant j'arrive pas à get le player dans le broadcast.

2022-11-26 17:08 UTC, romain22222 requested changes

2022-11-26 17:08 UTC, romain22222 commented on src/core/constants/HelpConstants.ts
> +		NOTIFICATIONS: ["notifications", "n", "notification",
à voir s'il faudrait pas en rajouter d'autres / remettre les anciens afin de rediriger vers la commande

2022-11-26 17:08 UTC, romain22222 commented on src/core/constants/NotificationsConstants.ts
> +}
3 choses : 

- les 3 scopes sont transformables en un seul énum, ce qui fait qu'on aurait en bdd des nombres et non des strings
- pourquoi dmvalue vaut -1 ? et pourquoi pas 0 EN NOMBRE et non en chaine ?
- pourquoi NO_NOTIFICATION est une string qui vaut null ??? mets moi une chaine vide ou autre, mais please pas le null

2022-11-26 17:08 UTC, romain22222 commented on src/core/constants/PlayersConstants.ts
> +		NOTIFICATIONS: "-1"
à changer du coup

2022-11-26 17:08 UTC, romain22222 commented on src/core/database/game/migrations/004-edit-notifications.ts
> +		SET players.notifications = "-1"
pareil à changer

2022-11-26 17:08 UTC, romain22222 commented on src/core/database/game/models/Player.ts
> +	public async getCumulativeAttack(playerActiveObject: playerActiveObjects): Promise<number> {
pourquoi le refact ? techniquement c'est tous les objets du joueur

la même pour les deux du dessous

2022-11-26 18:15 UTC, BastLast commented on resources/text/commands/guildDaily.json
> +				"description": "\uD83C\uDFDF️ {pseudo} a récupéré le bonus journalier de votre guilde sur le serveur {serveur}.\n\n"
Nan mais c'est normal cette écriture, on garde ça

2022-11-26 20:18 UTC, voltou91 commented on src/core/database/game/models/Player.ts
> +	public async getCumulativeAttack(playerActiveObject: playerActiveObjects): Promise<number> {
Ouais ça c juste que deepsource me gueulait dessus parce que ça avait le même nom que l'objet.

2022-11-26 20:20 UTC, romain22222 commented on src/core/database/game/models/Player.ts
> +	public async getCumulativeAttack(playerActiveObject: playerActiveObjects): Promise<number> {
dans ce cas, renomme le type en "PlayerActiveObjects", je sais pas qui a fait le type, mais un type doit en principe avoir une majuscule pour justement le différencier d'une variable

2022-11-26 20:21 UTC, voltou91 commented on src/core/database/game/models/Player.ts
> +	public async getCumulativeAttack(playerActiveObject: playerActiveObjects): Promise<number> {
Ok je ferais ça.

2022-11-26 20:25 UTC, voltou91 commented on src/core/constants/NotificationsConstants.ts
> +}
Alors enfaite on a décidé que DM_VALUE vallait -1, aucune notifications valait 0 et tout le reste c'était l'id d'un channel. De base oui c'était un nombre sauf que les id Discord sont en string car elles sont trop grandes. On ne pouvait pas enregistrer l'id des salons dans la base de données (ça faisait une erreur) en tant que nombre donc c'est devenu un string.

2022-11-26 21:01 UTC, romain22222 commented on src/core/constants/NotificationsConstants.ts
> +}
du coup pourquoi aucune notification vaut ici null et non 0 ?

et du coup faut bien refact les scopes en enum

2022-11-27 10:50 UTC, BastLast commented on src/core/database/game/migrations/004-edit-notifications.ts
> +	await context.changeColumn("players","dmNotification", DataTypes.STRING);
@voltou91  c'est fait ça ?

2022-11-27 12:05 UTC, voltou91 commented on src/core/database/game/migrations/004-edit-notifications.ts
> +	await context.changeColumn("players","dmNotification", DataTypes.STRING);
C'est juste remplacer le code en dur par les constantes ?

2022-11-27 13:02 UTC, voltou91 commented on src/core/constants/HelpConstants.ts
> +		NOTIFICATIONS: ["notifications", "n", "notification",
Je voit pas quoi rajouter, y en a quand même 11. Dans mon prochain commit j'ai corriger les fautes genre 'désa**ca**ctiver".

2022-11-27 13:03 UTC, voltou91 commented on resources/text/models/players.json
> +			"dmDisabledFooter": "Vous avez bloqué vos messages privés, ou vous avez désactivé les notifications. Si vous voulez activer les notifications, faites la commande notification et activez les messag
Les footers ne prennent aucun formatage, t'as le droit juste de mettre du texte puis c'est tout.

2022-11-27 13:17 UTC, voltou91 commented on src/core/database/game/models/Player.ts
> +	private async checkChannelAccess(user: User, embed: DraftBotEmbed, language: string): Promise<void> {
Je t'avoue que maintenant dans l'état actuelle de la fonction, je la voit que dans player. J'utilise le player dedans et elle sert exclusivement à l'envoie de la notif. Par contre ce que je peux faire c'est mettre le broadcast dans une fonction dans l'utils des messages comme ça tout le monde peux envoyer un embed sur n'importe quel salon (à condition d'avoir l'id).

2022-11-27 17:27 UTC, BastLast approved these changes

2022-11-27 17:39 UTC, Feiryn commented on src/commands/player/ProfileCommand.ts
> +async function getStatisticField(profileModule: TranslationModule, askedPlayer: Player, playerActiveObjects: PlayerActiveObjects): Promise<EmbedField> {
Pourquoi ce type prend une majuscule maintenant ? Les types commencent par une minuscule

2022-11-27 17:41 UTC, BastLast commented on src/commands/player/ProfileCommand.ts
> +async function getStatisticField(profileModule: TranslationModule, askedPlayer: Player, playerActiveObjects: PlayerActiveObjects): Promise<EmbedField> {
parce que @romain22222  s'est trompé

2022-11-27 17:47 UTC, Feiryn commented on src/commands/player/ProfileCommand.ts
> +async function getStatisticField(profileModule: TranslationModule, askedPlayer: Player, playerActiveObjects: PlayerActiveObjects): Promise<EmbedField> {
Ok c'est une interface pas un type j'ai rien dit

2022-11-27 17:48 UTC, Feiryn commented on src/core/utils/MessageUtils.ts
> +		await client.channels.fetch(context.player.notifications).then(async (channel) => {
Les await sont inutiles, vu que y a un then

2022-11-27 17:48 UTC, Feiryn commented on src/core/utils/MessageUtils.ts
> +			await (<TextBasedChannel>channel).send(context.embedNotification);
Ici pas besoin d'await, juste un then

2022-11-27 17:50 UTC, Feiryn commented on src/core/utils/MessageUtils.ts
> +	if (!channelAccess[1]) {
Ca va pas ça, channelAccess c'est un tableau avec une taille égale au nombre de shards, donc si t'as 5 shards, t'auras un tableau de 5 booléens, et faut check si les 5 booléens sont à false

2022-11-27 17:50 UTC, Feiryn commented on src/core/utils/MessageUtils.ts
> +	if (!channelAccess[1]) {
Et puis c'est pas forcément le shard 0 qui envoie la commande

2022-11-27 20:22 UTC, Feiryn approved these changes

2022-11-27 20:35 UTC, romain22222 approved these changes

2022-11-27 20:36 UTC, merged