Events refactoring
DraftBot-A-Discord-Adventure/DraftBot pull request #1669
Opened 2022-12-19 15:37 UTC by Feiryn

Pour préparer le karma et le pve

J'ai déjà relu les json, donc sauf si vous avez 1h à perdre vous n'avez pas besoin de relire

2022-12-19 15:49 UTC, Feiryn commented
C'est good, deepsource c'est à ignorer et codescene flemme

2022-12-19 16:22 UTC, Pietagorh commented on src/core/events/BigEventsController.ts
> +let globalBigEvents: BigEvent[];
Pourquoi ils sont en dehors plutôt que d'être des propriétés ?

2022-12-20 14:17 UTC, voltou91 requested changes

2022-12-20 14:31 UTC, Feiryn commented on src/commands/admin/testCommands/Map/ForceReportTestCommand.ts
> -	}
Rien n'indique que les évents sont dans un ordre continu, et au pire ça crash après car ça n'existe pas, pas grave

2022-12-20 15:15 UTC, voltou91 approved these changes

2022-12-20 15:15 UTC, merged