add verification end travel notification + fix bug bad name notification #1673
DraftBot-A-Discord-Adventure/DraftBot pull request #1675
Opened 2022-12-25 13:21 UTC by voltou91

…ion #1673

2022-12-27 09:22 UTC, BastLast commented
merci de toujours ouvrir une issue pour un bug, pour le soucis de pp l'issue est #1681

2022-12-27 19:31 UTC, Feiryn requested changes

2022-12-27 19:31 UTC, Feiryn commented on src/core/maps/TravelTime.ts
> +		const date = new Date();
Faudrait mettre ça dans une fonction à part, elle commence à devenir grande et elle est pas super évidente à comprendre

2022-12-28 20:53 UTC, BastLast approved these changes

2022-12-28 20:53 UTC, BastLast commented on src/core/utils/MessageUtils.ts
> +			Translations.getModule("commands.report", "fr").format("newBigEvent", {destination: (await player.getDestination()).getDisplayName("fr")})
il faut utiliser les constantes et non "en"

2022-12-28 20:59 UTC, merged