début d'équilibrage #1695
DraftBot-A-Discord-Adventure/DraftBot pull request #1696
Opened 2022-12-30 19:39 UTC by BastLast

2023-01-06 22:30 UTC, BastLast commented
J'ai terminé mon travail ici, le détail de ce qui a été fait est dans #1695

2023-01-06 22:34 UTC, Pietagorh commented on resources/text/commands/profile.json
>  			"statistique": {
HUH le nom

2023-01-07 11:41 UTC, Feiryn commented on src/commands/player/ProfileCommand.ts
> +			cumulativeMaxHealth: await askedPlayer.getMaxCumulativeFightPoint(),
Est-ce qu'on pourrait pas faire mieux pour le profile ? Avec ça il commence à devenir beaucoup trop chargé. Peut-être une réaction style /switch pour afficher la partie moins intéressante ?

2023-01-07 11:46 UTC, Feiryn commented on src/core/fights/actions/interfaces/alterations/burned.ts
> +		const poisonTranslationModule = Translations.getModule(`fightactions.${this.name}`, language);
Le petit copié collé

2023-01-07 16:21 UTC, BastLast commented on src/core/fights/actions/interfaces/alterations/burned.ts
> +		const poisonTranslationModule = Translations.getModule(`fightactions.${this.name}`, language);
oups

2023-01-07 16:25 UTC, BastLast commented on src/commands/player/ProfileCommand.ts
> +			cumulativeMaxHealth: await askedPlayer.getMaxCumulativeFightPoint(),
j'ai un peu plus de temp alors je répond maintenant, déjà je pense que c'est pas le but de cette issue, je pense que si on doit retravailler autant le profil, il faut le faire dans une nouvelle issue

Pr avoir fait les tests là dessus sincerement c'est pas trop vénère ni surchargé, je ne pense pas que cela doit etre une priorité

2023-01-07 16:27 UTC, BastLast commented on src/commands/player/ProfileCommand.ts
> +			cumulativeMaxHealth: await askedPlayer.getMaxCumulativeFightPoint(),
si tu juges que c'est vraiment important, go créer une issue à part

2023-01-07 16:32 UTC, BastLast commented on resources/text/commands/profile.json
>  			"statistique": {
???????

2023-01-07 16:33 UTC, voltou91 commented on resources/text/commands/profile.json
>  			"statistique": {
c parce que c en français je suppose

2023-01-07 16:34 UTC, BastLast commented on resources/text/commands/profile.json
>  			"statistique": {
hannnn

2023-01-07 17:02 UTC, romain22222 requested changes

2023-01-07 17:02 UTC, romain22222 commented on src/core/fights/fighter/Fighter.ts
> +			return this.fightActionsHistory[this.fightActionsHistory.length - 2];
que se passe t il s'il y a deux altérations :doge:

2023-01-07 17:04 UTC, BastLast commented on src/core/fights/fighter/Fighter.ts
> +			return this.fightActionsHistory[this.fightActionsHistory.length - 2];
bah justement on va chercher la fightaction d'avant dans l'historique, qui est forcément pas une altération

2023-01-07 17:04 UTC, BastLast commented on src/core/fights/actions/interfaces/counterAttack.ts
> +		if (["ultimateAttack",
en effet c'est plus intelligent

2023-01-07 17:05 UTC, BastLast commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
non parce que vu qu'on fait le turn++ avant le if, le playing fighter a déjà changé

2023-01-07 17:12 UTC, BastLast commented on resources/text/models/players.json
> +				"classTierFive": ":bookmark: | Classes de palier 5 débloquées ! Pour plus d'informations sur les classes, les commandes {command:classesinfo} et {command:help}.",
jsp

2023-01-07 17:23 UTC, Pietagorh commented on src/core/constants/FightConstants.ts
> +	static readonly MAX_TURNS = 24;
J'préfère que ce soit le joueur avec la moins grande partie de sa vie
Genre en pourcentage
C'est plus fair

2023-01-07 17:24 UTC, Pietagorh commented on src/core/fights/actions/interfaces/counterAttack.ts
> +		if (["ultimateAttack",
/ rajouter un tag sur les actions

2023-01-07 17:26 UTC, BastLast commented on src/core/constants/FightConstants.ts
> +	static readonly MAX_TURNS = 24;
nope ça sera en nombre c'est jamais en % dans aucun jeu

2023-01-07 17:33 UTC, romain22222 commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
Bah pourquoi un tel malus pour le second joueur ? Tu crois pas que commencer est pas déjà un avantage suffisant pour le 1er joueur ?!

2023-01-07 17:34 UTC, romain22222 commented on resources/text/models/players.json
> +				"classTierFive": ":bookmark: | Classes de palier 5 débloquées ! Pour plus d'informations sur les classes, les commandes {command:classesinfo} et {command:help}.",
et ici j'ai pas compris pourquoi avoir fermé la conv, l'issue est réelle

2023-01-07 17:35 UTC, BastLast commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
c'est pas un malus, la regen de souffle a lieu avant ton tour donc la en gros ça donnait un bonus de souffle au j2 alors qu'il avais jamais joué. Basiquement c'était un bonus énorme au j2

2023-01-07 17:37 UTC, romain22222 commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
Sauf que jouer en second est très TRES pénalisant dans beaucoup de cas, je pense que c'est fair de donner un ptit avantage au second, comme dans hearthstone (avec la pièce), ou encore dans shadowverse (avec le crystal d'évolution supplémentaire). A la limite si tu trouves qu'une full regen est trop pétée, donne uniquement une partie de la regen ?

2023-01-07 17:38 UTC, BastLast commented on src/core/fights/fighter/Fighter.ts
> +			return this.fightActionsHistory[this.fightActionsHistory.length - 2];
toute cette pr a été testé 50K fois, 
ya jamais 2 alté d'affilé parce que un joueur peut pas avoir 2 altés en meme temps

2023-01-07 17:38 UTC, BastLast commented on resources/text/models/players.json
> +				"classTierFive": ":bookmark: | Classes de palier 5 débloquées ! Pour plus d'informations sur les classes, les commandes {command:classesinfo} et {command:help}.",
parce que je l'ai fixé en local, le commit arrive

2023-01-07 17:40 UTC, romain22222 commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
Exemple à la con : donner Math.floor((ta vitesse / vitesse adverse) * regen souffle) au second joueur (ca donne une full regen contre un miroir parfait, qui balance les fights compliqués, et ca donne un peu de souffle aux joueurs moins rapides, en plus ca reflète la réalité : si dans un combat l'un est bien plus rapide que l'autre, le second n'aura pas beaucoup le temps de respirer, mais si les deux sont à vitesse proche, il aura plus de temps de respirer avant)

2023-01-07 17:40 UTC, romain22222 commented on src/core/fights/fighter/Fighter.ts
> +			return this.fightActionsHistory[this.fightActionsHistory.length - 2];
ok

2023-01-07 17:41 UTC, BastLast commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
ça a été testé et c'était pété,

2023-01-07 17:42 UTC, BastLast commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
avec le full regen

2023-01-07 17:43 UTC, romain22222 commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
bah du coup une partie de la regen, comme j'ai proposé

2023-01-07 17:43 UTC, BastLast commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
l'idée du regen partiel peut etre explorée dans le futur, mais dans cette v1, fallait participer aux sessions d'équilibrage si tu voulais avoir ton mot a dire 👅

2023-01-07 17:44 UTC, romain22222 commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
si tu veux pas le faire rn, fais une issue 😜

2023-01-07 17:45 UTC, BastLast commented on src/core/fights/actions/interfaces/counterAttack.ts
> +		if (["ultimateAttack",
rajouter un tag sur les actions ne serait pas utile dans ce cas précis. un tag est plus fait pour si le truc est réutilisé à plusieurs endroits

2023-01-07 17:51 UTC, BastLast commented on src/core/fights/FightController.ts
> +				// No regen on first turn for the second player
Yaura d'autre sessions d'équilibrage des combats et yaura ça dedans  si  besoin no worries

2023-01-07 18:06 UTC, romain22222 approved these changes

2023-01-07 18:08 UTC, merged