PVE logs #1765
DraftBot-A-Discord-Adventure/DraftBot pull request #1976
Opened 2023-06-07 22:26 UTC by Feiryn

2023-06-08 21:39 UTC, Feiryn commented
Vas-y je give up je laisse comme ça, vous pouvez review

2023-06-09 21:39 UTC, voltou91 requested changes

2023-06-09 21:39 UTC, voltou91 commented on src/commands/player/FightCommand.ts
> +	const fightLogId = await draftBotInstance.logsDatabase.logFight(fight);
Mettre ça dans le if, afin de nous épargner une requête pour rien si c'était un fight friendly

2023-06-09 21:45 UTC, Feiryn commented on src/commands/player/FightCommand.ts
> +	const fightLogId = await draftBotInstance.logsDatabase.logFight(fight);
Non faut log les fights friendly aussi

2023-06-09 21:48 UTC, voltou91 approved these changes

2023-06-09 21:49 UTC, merged