Moresmallfixes
DraftBot-A-Discord-Adventure/DraftBot pull request #2109
Opened 2023-08-03 22:40 UTC by BastLast

2023-08-03 22:43 UTC, BastLast commented
@DraftBot-A-Discord-Adventure/testers Une fois que ça sera en pré-release j'aimerai un test complet du gd.

Ce badge peut être gagné si : La guilde est classée au classement de guilde.
La guilde est dans le top 25 des meilleures guilde au classement de guilde
Au moins une personne dans la guilde n'a pas déjà le badge
La guilde est niveau 100 ou plus.

Merci de check que ça fonctionne correctement.

2023-08-04 08:15 UTC, romain22222 requested changes

2023-08-04 08:15 UTC, romain22222 commented on src/commands/guild/GuildDailyCommand.ts
> +	draftBotInstance.logsDatabase.logGuildDaily(guildLike.guild, GuildDailyConstants.REWARD_TYPES.BADGE).then();
Y a inversion des deux badges

2023-08-04 08:15 UTC, romain22222 commented on src/core/Constants.ts
> +		LIST_FOR_GIVE_BADGE_COMMAND: [
Pourquoi des badges ont disparus et si c est le cas faut faire une migration pour le retirer de ceux qui en ont

2023-08-04 08:15 UTC, romain22222 commented on src/core/constants/GuildConstants.ts
> +	static SUPER_BADGE_MIN_RANK = 25;
Ce serait plus le rang maximal

2023-08-04 08:16 UTC, BastLast commented on src/commands/guild/GuildDailyCommand.ts
> +	draftBotInstance.logsDatabase.logGuildDaily(guildLike.guild, GuildDailyConstants.REWARD_TYPES.BADGE).then();
Je les ai juste retiré de la commande givebadge parce que yavais trop d'arguments et que les badge manager ont pas besoin de les donner

2023-08-04 08:16 UTC, BastLast commented on src/core/Constants.ts
> +		LIST_FOR_GIVE_BADGE_COMMAND: [
Je les ai juste retiré de la commande givebadge parce que yavais trop d'arguments et que les badge manager ont pas besoin de les donner

2023-08-04 08:17 UTC, BastLast commented on src/core/constants/GuildConstants.ts
> +	static SUPER_BADGE_MIN_RANK = 25;
Certe

2023-08-04 16:36 UTC, romain22222 commented on src/core/constants/GuildDailyConstants.ts
> +			guildXP: 150,
je viens de tilter un truc : est ce qu'une guilde au niveau 150 peut gagner de l'xp de guilde avec ton système.

2023-08-04 16:48 UTC, BastLast commented on src/core/constants/GuildDailyConstants.ts
> +			guildXP: 150,
oui je sais pas pk j'ai changé ça c une erreur

2023-08-04 16:48 UTC, BastLast commented on src/core/constants/GuildDailyConstants.ts
> +			guildXP: 150,
je vais en profiter pour ajouter un test unitaire

2023-08-04 17:07 UTC, BastLast commented on src/commands/guild/GuildDailyCommand.ts
> +		if (!member.addBadge(Constants.BADGES.POWERFUL_GUILD)) {
fixé

2023-08-04 17:07 UTC, BastLast commented on src/core/constants/GuildDailyConstants.ts
> +			guildXP: 150,
fixé

2023-08-05 06:53 UTC, romain22222 approved these changes

2023-08-05 06:53 UTC, romain22222 commented on test/unit/commands/guildDailyCommand.test.ts
> +test("All guild daily reward objects have the same amount of properties", () => {
bon loin d'être urgent, mais faudrait plutot un test qui check s'ils ont les mêmes properties au lieu d'un qui check le nombre, car tu pourrais avoir une connerie du genre un mec qui push le tableau mais a fait une typo sur l'une d'elle

2023-08-05 11:16 UTC, Feiryn commented on test/unit/commands/guildDailyCommand.test.ts
> +test("All guild daily reward objects have the same amount of properties", () => {
C'est surtout que c'est un void donc ça n'a pas de sens de return

2023-08-05 17:45 UTC, merged