fix #2148
DraftBot-A-Discord-Adventure/DraftBot pull request #2179
Opened 2023-09-19 20:48 UTC by Noelle-Ai

Fix du bug de la potion non consommée en PVE

2023-09-19 20:50 UTC, symsym-1629 commented
Ayant aidé à régler ca, j'approuve 👍 Mais ca compte pour du beurre :p

2023-09-19 22:44 UTC, BastLast requested changes
Ce changement ne va pas résoudre le problème, si on fait ça, les joueurs vont gagner de la gloire à la fin du combat contre un monstre ou ce genre de choses. Le fix de cette issue n'est pas aussi simple que ça et il faut bien penser à tous les cas de figure

2023-09-20 05:51 UTC, Noelle-Ai commented
Aucune gloire gagnée de mon côté

2023-09-20 05:57 UTC, Noelle-Ai commented
Je comprends, je vais regarder les potentiels effets secondaires

2023-09-20 10:18 UTC, Noelle-Ai commented
Bien, après avoir effectué quelques tests dont les screens sont ci-joints, voilà les conclusions que j'en retire :

- Dans les deux cas, combat gagné comme perdu, la gloire ne change pas
- Dans les deux cas, la potion est bel et bien consommée
- Aucune anomalie d'altération ou quoi que ce soit sur le profil (du moins je n'en ai pas trouvé sur les 4, avant et après chaque combat), ni dans l'inventaire
- J'ai détecté un bug de traduction dont le screen est ci-joint également

Dois-je ouvrir une issue pour cette erreur de traduction ?


<img width="859" alt="combat_perdu_profil_fin" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/b75e1658-de05-4541-9b30-c42fd9bc2001">
<img width="1108" alt="combat_perdu_intro" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/d404de3d-3cae-4969-8bec-8c505d855ecc">
<img width="1091" alt="combat_perdu_fin" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/ebb36f20-8d71-4b13-864e-33c3eef818f1">
<img width="951" alt="combat_perdu_bug_translation" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/b0d99df5-be16-4333-8049-7c7708045632">
<img width="675" alt="combat_perdu_avant" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/b58a4916-d337-4374-8b74-ef4bd2c7b87c">
<img width="472" alt="combat_gagne_profil_fin" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/4d92c5de-d874-45eb-9778-55c5ee5cc7a8">
<img width="1111" alt="combat_gagne_fin" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/43002752-2ec7-4b44-b952-3b35984daac3">
<img width="1106" alt="combat_gagne_deroule" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/8dd8b746-bc72-403c-aeb6-3b57794397e6">
<img width="660" alt="combat_gagne_avant" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/416acc36-98f6-49cd-87ec-474edc003a0d">
<img width="524" alt="combat_gagne_apres" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/74e5bf32-9590-4ae8-887f-9d0cc1f91666">

2023-09-20 10:35 UTC, BastLast commented
Et dans les logs c'est traité correctement ?

2023-09-20 10:35 UTC, BastLast commented
Pr l'erreur de trad go la report au bon endroit

2023-09-20 10:36 UTC, voltou91 commented
Nah le bug de trad je l'ai déjà report à Romain mdrrr, il apparaît déjà dans le console quand on lance le bot. C'est juste un oublie de "sunny" dans deux catégories.

2023-09-20 10:37 UTC, voltou91 commented
> a
Bon bah j'ai rien dit, drapht a parlé

2023-09-20 10:37 UTC, BastLast commented
Pr l'erreur de trad go la report au bon endroit

2023-09-20 10:40 UTC, Noelle-Ai commented
> Et dans les logs c'est traité correctement ?

Pas d'erreur apparente non plus (screen ci-joint)
Par ailleurs, à titre indicatif, j'ai fait des tests de PVP amical ou non avec pour chacun win et perte, aucune anomalie non plus, de même lorsqu'un joueur est en PVE et qu'un autre tente de le combattre, impossible car il est sur l'île mystérieuse donc pas d'anomalie de ce côté-ci non plus
<img width="875" alt="logs" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/f9f7fa6d-dde1-419b-9e58-9b70e048788b">

2023-09-20 10:40 UTC, Noelle-Ai commented
> Pr l'erreur de trad go la report au bon endroit

Qui est ? Désolée ^^'

2023-09-20 10:41 UTC, voltou91 commented
> Pr l'erreur de trad go la report au bon endroit

L'issue des erreurs d'ort

> > Et dans les logs c'est traité correctement ?
> 
> Pas d'erreur apparente non plus (screen ci-joint) Par ailleurs, à titre indicatif, j'ai fait des tests de PVP amical ou non avec pour chacun win et perte, aucune anomalie non plus, de même lorsqu'un joueur est en PVE et qu'un autre tente de le combattre, impossible car il est sur l'île mystérieuse donc pas d'anomalie de ce côté-ci non plus <img alt="logs" width="875" src="https://user-images.githubusercontent.com/46852063/269256273-f9f7fa6d-dde1-419b-9e58-9b70e048788b.png">

C vrmt écrit "weatherContinues.sunny" mdrrr

2023-09-20 10:42 UTC, voltou91 commented
> > Pr l'erreur de trad go la report au bon endroit
> 
> Qui est ? Désolée ^^'

Tkt je l'ai fait pour toi :)

2023-09-20 10:42 UTC, Noelle-Ai commented
Aaah tu parlais de l'erreur de trad, j'ai cru que BastLast demandait comment le PVE était gérer dans les logs mdrrr

2023-09-20 10:42 UTC, Noelle-Ai commented
> > > Pr l'erreur de trad go la report au bon endroit
> > 
> > 
> > Qui est ? Désolée ^^'
> 
> Tkt je l'ai fait pour toi :)

Par ailleurs comment cela se passe pour en régler une ? C'est Drapht qui s'en occupe ou je peux faire une pr ?

2023-09-20 10:44 UTC, voltou91 commented
> > > > Pr l'erreur de trad go la report au bon endroit
> > > 
> > > 
> > > Qui est ? Désolée ^^'
> > 
> > 
> > Tkt je l'ai fait pour toi :)
> 
> Par ailleurs comment cela se passe pour en régler une ? C'est Drapht qui s'en occupe ou je peux faire une pr ?

Généralement c'est une pr que quelqu'un fait vers la fin de la maj, c'est une issue fourre tout pour toutes les erreurs de trads rapporté 
L'issue c'est la #2151

2023-09-20 10:45 UTC, Noelle-Ai commented
> > > > > Pr l'erreur de trad go la report au bon endroit
> > > > 
> > > > 
> > > > Qui est ? Désolée ^^'
> > > 
> > > 
> > > Tkt je l'ai fait pour toi :)
> > 
> > 
> > Par ailleurs comment cela se passe pour en régler une ? C'est Drapht qui s'en occupe ou je peux faire une pr ?
> 
> Généralement c'est une pr que quelqu'un fait vers la fin de la maj, c'est une issue fourre tout pour toutes les erreurs de trads rapporté L'issue c'est la #2151

Ooook une pr qui règle toutes les erreurs c'est ça ?

2023-09-20 10:47 UTC, voltou91 commented
> > > > > > Pr l'erreur de trad go la report au bon endroit
> > > > > 
> > > > > 
> > > > > Qui est ? Désolée ^^'
> > > > 
> > > > 
> > > > Tkt je l'ai fait pour toi :)
> > > 
> > > 
> > > Par ailleurs comment cela se passe pour en régler une ? C'est Drapht qui s'en occupe ou je peux faire une pr ?
> > 
> > 
> > Généralement c'est une pr que quelqu'un fait vers la fin de la maj, c'est une issue fourre tout pour toutes les erreurs de trads rapporté L'issue c'est la #2151
> 
> Ooook une pr qui règle toutes les erreurs c'est ça ?

Toutes les erreurs de trads et typos, oui mais on la fait vers la fin de la maj pour toute les réglées en même temps :)

2023-09-20 10:49 UTC, Noelle-Ai commented
> > > > > > > Pr l'erreur de trad go la report au bon endroit
> > > > > > 
> > > > > > 
> > > > > > Qui est ? Désolée ^^'
> > > > > 
> > > > > 
> > > > > Tkt je l'ai fait pour toi :)
> > > > 
> > > > 
> > > > Par ailleurs comment cela se passe pour en régler une ? C'est Drapht qui s'en occupe ou je peux faire une pr ?
> > > 
> > > 
> > > Généralement c'est une pr que quelqu'un fait vers la fin de la maj, c'est une issue fourre tout pour toutes les erreurs de trads rapporté L'issue c'est la #2151
> > 
> > 
> > Ooook une pr qui règle toutes les erreurs c'est ça ?
> 
> Toutes les erreurs de trads et typos, oui mais on la fait vers la fin de la maj pour toute les réglées en même temps :)

D'accord !

2023-09-20 11:35 UTC, BastLast commented
@Feiryn  d'autres idées de trucs qui pourraient ne pas aller ?

2023-09-20 11:36 UTC, BastLast commented
> > Et dans les logs c'est traité correctement ?
> 
> Pas d'erreur apparente non plus (screen ci-joint) Par ailleurs, à titre indicatif, j'ai fait des tests de PVP amical ou non avec pour chacun win et perte, aucune anomalie non plus, de même lorsqu'un joueur est en PVE et qu'un autre tente de le combattre, impossible car il est sur l'île mystérieuse donc pas d'anomalie de ce côté-ci non plus <img alt="logs" width="875" src="https://user-images.githubusercontent.com/46852063/269256273-f9f7fa6d-dde1-419b-9e58-9b70e048788b.png">

je parlais des logs dans la bdd des logs

2023-09-20 11:59 UTC, Noelle-Ai commented
> > > Et dans les logs c'est traité correctement ?
> > 
> > 
> > Pas d'erreur apparente non plus (screen ci-joint) Par ailleurs, à titre indicatif, j'ai fait des tests de PVP amical ou non avec pour chacun win et perte, aucune anomalie non plus, de même lorsqu'un joueur est en PVE et qu'un autre tente de le combattre, impossible car il est sur l'île mystérieuse donc pas d'anomalie de ce côté-ci non plus <img alt="logs" width="875" src="https://user-images.githubusercontent.com/46852063/269256273-f9f7fa6d-dde1-419b-9e58-9b70e048788b.png">
> 
> je parlais des logs dans la bdd des logs

Aah d'accord je vois, il y a une commande pour regarder ça ? En regardant avec mon logiciel dans la list des potions sent je vois bien que la potion est consommée
<img width="945" alt="image" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/db9a2462-19a9-4e73-9034-410f4254db24">
<img width="1680" alt="image" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/f01483c5-cd20-4734-bf86-17095a211279">

2023-09-22 16:53 UTC, BastLast commented
@Feiryn je vois pas ce qu'ils auraient oubliés ? tu penses à un truc ?

2023-09-28 12:11 UTC, BastLast commented
@Feiryn  pour moi ça me parait bon mais je t'ai vu emettre des réserve sur discord, possible de check en speed pour savoir si on peut merge ?

2023-09-30 08:06 UTC, Feiryn commented
Je pense que c'est bon

2023-10-04 10:09 UTC, Feiryn approved these changes

2023-10-04 10:10 UTC, Feiryn approved these changes

2023-10-04 10:11 UTC, merged