fix bad display for statistics at 0 #2008
DraftBot-A-Discord-Adventure/DraftBot pull request #2260
Opened 2023-10-26 10:28 UTC by voltou91

2023-10-26 11:55 UTC, BastLast requested changes
Nan c'est dégeu ça c'est mort D'autant que vu que ça le faisais que sur 2 des 3 fonctions il y a un fix à faire dans la fonction directement

2023-10-26 14:41 UTC, BananePlantain commented
C'est l'objet à 25 pas la potion (l'objet dépend bien de la statistique de base là ou la potion passe outre)

2023-10-26 21:57 UTC, BastLast commented
> Bah sinon l'issue n'est pas un bug, vu que ça fait bien bouclier à 0, la popo à 25 et l'arme à -20 donc c'est normal que ça affiche 5 vu que c'est la potion qui les donnent. Donc soit j'ai pas compris ce que tu voulais me dire, soit c'est juste pas un bug. Tout dépend de si on veut que à partir du moment où ta base est à 0 alors la potion ou l'item ne donne pas de bonus.

ya un bug dans le calcul mais faut le fix autrement qu'avec un gros if

2023-11-13 12:15 UTC, BastLast commented
je ferme cette pr vu que les changements demandés n'ont pas été effectués, go la rouvrir avec les changements dans les formules :)

2023-11-13 12:15 UTC, closed without merging