Add new items.
DraftBot-A-Discord-Adventure/DraftBot pull request #2295
Opened 2023-11-18 21:44 UTC by Aikoo-Sama

2023-11-19 05:47 UTC, Nargacaura requested changes

2023-11-19 05:47 UTC, Nargacaura commented on resources/text/objects/82.json
> +		"fr": "Le Script de Easy",
Peut-être retirer le "le" d'ici, sinon ça ferait "son *le* script" dans le mini-event d'IOP.

2023-11-19 05:47 UTC, Nargacaura commented on resources/text/objects/85.json
> +		"fr": "Roulo PQ",
La typo était volontaire? J'avais plus vu comme "Roul**eau** PQ".

2023-11-19 05:47 UTC, Nargacaura commented on resources/text/weapons/92.json
> +		"fr": "Le Game Over",
Là aussi, faudra retirer le "le" (et le "the" d'ici).

2023-11-19 05:47 UTC, Nargacaura commented on resources/text/weapons/93.json
> +		"fr": "Le Torchon du Cuisinier",
Ici aussi, y'a le "le"/"the" en trop.

2023-11-19 18:30 UTC, BastLast commented
du coup j'ai voulu faire un passage dessus mais j'ai vite arrété parce que ya trop de trucs qui allaient pas, c'est pas de ta faute @Aikoo-Sama  j'aurai du expliquer le système qui ets un peu obscure.


chaque armure DOIT avoir une rawDefense et ne DOIT PAS avoir une raw autre chose

(et inversement pr les autres uen weapon DOIT avoir une rawAttack et pas de rawDefense)

les valeurs bonus autre que la stat de bases sont harcodé avec "defense speed et attack" 

j'en ai profité pour fix l'egide puissante qui était broken

2023-11-19 18:30 UTC, BastLast commented
je te laisse faire un passage sur les nouveaux items je referai une session d'équilibrage later

2023-11-19 18:55 UTC, Aikoo-Sama commented on resources/text/objects/85.json
> +		"fr": "Roulo PQ",
Oui elle l'est.

2023-11-19 18:55 UTC, Aikoo-Sama commented
> du coup j'ai voulu faire un passage dessus mais j'ai vite arrété parce que ya trop de trucs qui allaient pas, c'est pas de ta faute @Aikoo-Sama j'aurai du expliquer le système qui ets un peu obscure.
> 
> chaque armure DOIT avoir une rawDefense et ne DOIT PAS avoir une raw autre chose
> 
> (et inversement pr les autres uen weapon DOIT avoir une rawAttack et pas de rawDefense)
> 
> les valeurs bonus autre que la stat de bases sont harcodé avec "defense speed et attack"
> 
> j'en ai profité pour fix l'egide puissante qui était broken

Okay, je note tout ça, vraiment désolée. Y'a-t-il d'autres choses que je dois savoir avant de repasser dessus ? Pour les objets, ou potions.

2023-11-19 23:40 UTC, BastLast commented
> > du coup j'ai voulu faire un passage dessus mais j'ai vite arrété parce que ya trop de trucs qui allaient pas, c'est pas de ta faute @Aikoo-Sama j'aurai du expliquer le système qui ets un peu obscure.
> > chaque armure DOIT avoir une rawDefense et ne DOIT PAS avoir une raw autre chose
> > (et inversement pr les autres uen weapon DOIT avoir une rawAttack et pas de rawDefense)
> > les valeurs bonus autre que la stat de bases sont harcodé avec "defense speed et attack"
> > j'en ai profité pour fix l'egide puissante qui était broken
> 
> Okay, je note tout ça, vraiment désolée. Y'a-t-il d'autres choses que je dois savoir avant de repasser dessus ? Pour les objets, ou potions.

tkt au final je me suis motivé pour faire la partie chiante mdr :) Merci pour ton aide en vrais yavais que 4 items qui avaient un soucis je crois.

j'ai fait un passage sur tous les nouveaux items et certains des anciens, c'est pas totalement parfait niveau équilibrage j'ai vu 2/3 trucs pas logiques mais ça ira pour le moment :)

j'ai changé certains items pour combler des trou dans les items genre et offrir des combinaison de stats impossibles avant :)

2023-11-19 23:41 UTC, BastLast commented
détail de l'équilibrage fait sur les items déjà existants : 🛡️ Égide puissante : Attaque - 44%, Défense + 55%
🧱 Légo : Rareté +1, Attaque + 142%
👁️ Œil de Fatalis : Attaque + 7%
🎸 Guitare terrifiante : Attaque + 10%
💎 Diamant kéraunique : Attaque + 8%
🥾 Bottes de Pégase : Vitesse + 18%
🏵️ Fleur de l'espoir : Vitesse + 38%
🚗 Kars : Vitesse + 40%

2023-11-19 23:42 UTC, BastLast approved these changes

2023-11-20 04:26 UTC, Nargacaura approved these changes

2023-11-20 07:58 UTC, merged

2023-11-29 21:04 UTC, BananePlantain commented
y a pas moyen d'inverser les stats des 2 objets de vitesse vu que ca renverse l'ordre présent auparavant (avant:bottes>fleur alors qu'après c'est le contraire)?