Update tiger event with Procion and Ravenclaw's comments and modifica…
DraftBot-A-Discord-Adventure/DraftBot pull request #2316
Opened 2023-11-25 13:27 UTC by Aikoo-Sama

Little changes in tiger event with Procion and Ravenclaw's suggestions.

2023-11-25 13:55 UTC, Aikoo-Sama commented
NE PAS MERGE, j'ai encore des edits à faire dessus.

2023-11-29 14:19 UTC, romain22222 approved these changes
texte + texte + texte = ok instant je fais confiance

2023-11-29 17:34 UTC, Nargacaura requested changes

2023-11-29 17:34 UTC, Nargacaura commented on resources/text/events/73.json
> +		"fr": "🐯 Cheminant avec nonchalance sur la Route des Merveilles, vous approchez d'un attroupement hétéroclite captivé par quelque chose hors de votre vue. Tout en avançant vers eux, vous voyez qu'i
C'est pas "vous **vous** approchez d'un attroupement"?

2023-11-29 17:34 UTC, Nargacaura commented on resources/text/events/73.json
> +		"en": "🐯 Walking nonchalantly along the Route des Merveilles, you approach a motley crew captivated by something out of your sight. As you walk towards them, you notice that they are forming a semi
"(...) baby tigers who**m** he is (...)"

2023-11-29 17:34 UTC, Nargacaura commented on resources/text/events/73.json
> +						"fr": "🖌️ Fasciné par ces adorables bébés, vous vous faufilez vers l'arrière de la roulotte du dresseur pour voir s'il y en a d'autres, afin d'en voler un pour le revendre à bon prix. Cependant
Plutôt "seule une chatte *allaitant ses petits* est présente", non?

2023-11-30 12:49 UTC, Nargacaura approved these changes

2023-11-30 12:53 UTC, merged