Report command part3
DraftBot-A-Discord-Adventure/DraftBot pull request #2446
Opened 2024-03-13 22:40 UTC by Feiryn

2024-03-13 22:50 UTC, BastLast requested changes

2024-03-13 22:50 UTC, BastLast commented on Discord/src/commands/player/ReportCommand.ts
> +	return desc;
imo ça serait plus clean d'avoir les retours à la ligne dans les fichiers de traduction

2024-03-13 22:50 UTC, BastLast commented on Discord/src/commands/player/ReportCommand.ts
> +	buttonCollector.on("collect", async (i: ButtonInteraction) => {
variable i à renommer, pas beau les variable d'une lettre

2024-03-13 22:50 UTC, BastLast commented on Discord/src/packetHandlers/handlers/NotificationsHandlers.ts
> +				i18nTr = time === 1 ? "commands:report.choseMap_one" : "commands:report.choseMap_other";
nombres magiques les 1 et le 60

2024-03-13 22:50 UTC, BastLast commented on Lang/fr/commands.json
> -  },
?????

2024-03-13 22:50 UTC, BastLast commented on Lang/en/commands.json
> -  },
?????

2024-03-14 06:08 UTC, Feiryn commented on Discord/src/commands/player/ReportCommand.ts
> +	return desc;
C'est pas vraiment possible vu que je ne sais pas combien il y en a

2024-03-14 06:09 UTC, Feiryn commented on Discord/src/packetHandlers/handlers/NotificationsHandlers.ts
> +				i18nTr = time === 1 ? "commands:report.choseMap_one" : "commands:report.choseMap_other";
Je vais pas créer une constante genre ONE = 1

2024-03-14 06:10 UTC, Feiryn commented on Lang/fr/commands.json
> -  },
Raah ils saoulent ces fichiers de trad

2024-03-14 08:51 UTC, BastLast commented on Discord/src/commands/player/ReportCommand.ts
> +	return desc;
flemme d'argumenter lol laissons le comme ça

2024-03-14 08:53 UTC, BastLast commented on Discord/src/packetHandlers/handlers/NotificationsHandlers.ts
> +				i18nTr = time === 1 ? "commands:report.choseMap_one" : "commands:report.choseMap_other";
ok je viens de check à quoi ça sert et faudrait regarder comment gérer les plurièles avec i18n parce que je pense pas qu'il faye faire comme tu as fait au vu de la documentation de i18n https://www.i18next.com/translation-function/plurals

2024-03-14 08:54 UTC, BastLast commented on Discord/src/packetHandlers/handlers/NotificationsHandlers.ts
> +				i18nTr = time === 1 ? "commands:report.choseMap_one" : "commands:report.choseMap_other";
my bad tu as fait comme il faut

2024-03-14 08:54 UTC, BastLast commented on Discord/src/packetHandlers/handlers/NotificationsHandlers.ts
> +				i18nTr = time === 1 ? "commands:report.choseMap_one" : "commands:report.choseMap_other";
my bad tu as pas fait comme il faut

2024-03-14 08:55 UTC, BastLast commented on Discord/src/packetHandlers/handlers/NotificationsHandlers.ts
> +				i18nTr = time === 1 ? "commands:report.choseMap_one" : "commands:report.choseMap_other";
i18next.t('key', {count: 0}); il faut juste balancer le count comme ça et paf

2024-03-14 08:57 UTC, BastLast commented on Discord/src/packetHandlers/handlers/NotificationsHandlers.ts
> +				i18nTr = time === 1 ? "commands:report.choseMap_one" : "commands:report.choseMap_other";
du coup en soit on peut juste balancer le time dans i18n direct

2024-03-14 22:16 UTC, BastLast approved these changes

2024-03-14 23:04 UTC, merged