Lottery SE
DraftBot-A-Discord-Adventure/DraftBot pull request #2514
Opened 2024-06-15 15:48 UTC by Feiryn

2024-06-17 22:10 UTC, romain22222 requested changes

2024-06-17 22:10 UTC, romain22222 commented on Core/src/core/smallEvents/lottery.ts
> +				}
je me demande si y'a pas moyen de passer les niveaux de difficulté en constante enum et de leur associer en clé la string du nom du collecteur

2024-06-17 22:10 UTC, romain22222 commented on Core/src/core/smallEvents/lottery.ts
> +				}
et passer en constante la money en magic constant

2024-06-17 22:10 UTC, romain22222 commented on Core/src/core/smallEvents/lottery.ts
> +					const coefficient = dataLottery.coefficients[levelKey];
y'aurait pas moyen d'extract method le gros switch case, ca alourdit la fonction principale alors que le but est clairement défini ici : "giveRewardToPlayer"

2024-06-17 22:10 UTC, romain22222 commented on Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
> +	@packetHandler(SmallEventLotteryWinPacket)
je viens de penser à un truc : est ce qu'on peut fournir dans le contexte de la fonction une variable user déjà initialisée directement via le décorateur ? vu que quasi tous les fronts vont en avoir besoin ca serait top, pareil pour interaction, quitte à instant quitter la fonction si pas d'interaction

2024-06-18 13:32 UTC, Feiryn commented on Core/src/core/smallEvents/lottery.ts
> +				}
C'est un oubli le magic number, je l'avais changé à d'autres endroits.
Pour l'enum, c'est se compliquer la tâche pour rien. Vu qu'un ne définit que 3 valeurs possibles, si on commence à associer une valeur autre ou comparer avec une valeur impossible ça ne compile pas. Avec un enum il faudra penser à passer le nom en lowercase et tout, ou faire un mapping enum => nom du niveau et inversement, c'est un peu chiant

2024-06-18 13:37 UTC, Feiryn commented on Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
> +	@packetHandler(SmallEventLotteryWinPacket)
Je sais pas, je préfère laisser quand même le choix à la fonction car il pourrait être récupéré d'autre part ou alors pas utilisé dans la fonction et donc ça fait un get en plus (via cache ou dans le pire des cas via keycloak donc une requête réseau)

2024-06-18 14:02 UTC, romain22222 commented on Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
> +	@packetHandler(SmallEventLotteryWinPacket)
seems fair, j'avais pas pensé à la partie réseau de ce changement je resolve then

2024-06-18 14:14 UTC, romain22222 approved these changes

2024-06-18 14:14 UTC, romain22222 commented on Core/src/core/smallEvents/lottery.ts
> +	canBeExecuted: (player: Player): Promise<boolean> => Promise.resolve(Maps.isOnContinent(player)),
```suggestion
	canBeExecuted: Maps.isOnContinent,
```
cf https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/draftbot-v5/Core/src/core/smallEvents/staffMember.ts

2024-06-18 14:14 UTC, romain22222 commented on Lib/src/packets/smallEvents/SmallEventLotteryPacket.ts
> +	level!: string;
du coup j'ai un peu plus compris pourquoi t'as mis des chaines en dur, et je vois que t'as typé pour faire en sorte d'autoriser uniquement les 3 bonnes chaines presque partout, manque que ici 😉
```suggestion
	level!: "easy" | "medium" | "hard";
```

2024-06-18 14:14 UTC, romain22222 commented on Core/src/core/smallEvents/lottery.ts
> +	levelKey: "easy" | "hard" | "medium",
```suggestion
	levelKey: LotteryLevelKey,
```

2024-06-18 20:07 UTC, merged