guildInvite
DraftBot-A-Discord-Adventure/DraftBot pull request #2678
Opened 2024-11-26 00:17 UTC by BastLast

2024-11-26 00:18 UTC, BastLast commented
@romain22222  je crois que @Kyusaor  était bloqué hier, tu as moyen de faire une review ?

2024-11-26 11:57 UTC, romain22222 requested changes

2024-11-26 11:57 UTC, romain22222 commented on Core/src/commands/guild/GuildInviteCommand.ts
> +		guildName: guild.name
même chose pas la peine de préciser inviting

2024-11-26 11:57 UTC, romain22222 commented on Core/src/commands/guild/GuildInviteCommand.ts
> +	}));
au lieu de faire une liste de booléens en fonction de l'erreur, fais un packet principal d'erreur dans le cas où le check ne passe pas, et crée différents packets en fonction de l'erreur que tu nommes en fonction. Ce sera aussi moins couteux côté front de le gérer car t'auras pas à faire une pile de conditions x2. Enfin, vu que l'on fait un collecteur, pas la peine de renvoyer un packet pour dire "tout va bien" (cf le dernier response.push)

2024-11-26 11:57 UTC, romain22222 commented on Core/src/commands/guild/GuildInviteCommand.ts
> +
que fais la fonction reload ?

2024-11-26 11:57 UTC, romain22222 commented on Core/src/commands/guild/GuildInviteCommand.ts
> +	await LogsDatabase.logsGuildJoin(guild, invitedPlayer.keycloakId, invitingPlayer.keycloakId);
on await pas le log dans la database (tout les rajouts à la database de logs sont fait en synchrone, en utilisant '.then()' au lieu de await

2024-11-26 11:57 UTC, romain22222 commented on Discord/src/commands/guild/GuildInviteCommand.ts
> +	return makePacket(CommandGuildInvitePacketReq, {invitedPlayer, invitingPlayer});
aussi, pourquoi mettre l'id keycloak dans un objet au lieu de le mettre directement dans le packet en mode invitedPlayerKeycloakId ?

2024-11-26 11:57 UTC, romain22222 commented on Discord/src/commands/guild/GuildInviteCommand.ts
> +		await buttonInteraction.editReply({
ici ca va planter, la buttonInteraction n'est pas faite pour être editReplied, faut faire un channel.send OU un originalInteraction.followup

2024-11-26 11:57 UTC, romain22222 commented on Discord/src/commands/guild/GuildInviteCommand.ts
> +		await buttonInteraction.editReply({
same as above

2024-11-26 11:57 UTC, romain22222 commented on Discord/src/utils/DiscordCollectorUtils.ts
> +		}
regroupe les options ensembles, y'a trop d'arguments là (en gros fais un options?: {accepted..., accept... etc}

2024-11-26 11:57 UTC, romain22222 commented on Discord/src/utils/DiscordCollectorUtils.ts
> +		let users: KeycloakUser[] = [];
au lieu de stocker une liste de KeycloakUsers, stocke une liste d'ids, et au lieu de faire un users.find, tu peux faire un users.includes, qui est bien plus rapide et plus lisible

2024-11-26 11:57 UTC, romain22222 commented on Discord/src/utils/DiscordCollectorUtils.ts
> +			const user = await KeycloakUtils.getDiscordUser(keycloakConfig, firstReaction.user.id, null);
variable inutilisée

2024-11-26 11:57 UTC, romain22222 commented on Lang/fr/commands.json
> +    "confirmDesc": ":question: Souhaitez vous rejoindre la guilde `{{guildName}}` ?",
emote à transférer dans DraftBotIcons

2024-11-26 11:57 UTC, romain22222 commented on Lang/fr/error.json
> +    "dead": "mort",
euhhhhhhhhhhhhhh ici c'est les textes de raison de bloquage, pourquoi y'a mort ?

2024-11-26 11:57 UTC, romain22222 commented on Lib/src/packets/interaction/ReactionCollectorGuildInvite.ts
> +	private readonly inviterKeycloakId: string;
ce serait pas plutôt "invited" au lieu de "inviter" ?

2024-11-26 15:15 UTC, Kyusaor commented on Core/src/commands/guild/GuildInviteCommand.ts
> +
Ca refresh l'instance de joueur, j'ai juste repris le pattern utilisé dans une des autres commandes guilde

2024-11-26 15:24 UTC, Kyusaor commented on Core/src/commands/guild/GuildInviteCommand.ts
> +	}));
Donc je fais un sendablePacket pour chaque cas dans la lib des packets de guildinvite avec le paramètre utile dedans à chaque fois et je check pour chaque packet coté front ensuite en gros?

2024-11-26 15:28 UTC, BastLast commented on Core/src/commands/guild/GuildInviteCommand.ts
> +
Oui ca faut garder c pr etre sur quon a bien la dernière version de ce qui a en bdd et que ca a pas changé entre le moment de la commande et le moment du click sur le bouton

2024-11-26 15:48 UTC, Kyusaor commented on Lang/fr/error.json
> +    "dead": "mort",
Pour le cas ou le joueur que tu veux inviter est clamsé

2024-11-26 15:50 UTC, romain22222 commented on Lang/fr/error.json
> +    "dead": "mort",
ouais mais c'est pas une raison de blocage (c'est quand t'es bloqué car y'a une commande en cours

2024-11-26 15:51 UTC, romain22222 commented on Lang/fr/commands.json
> +    "confirmDesc": ":question: Souhaitez vous rejoindre la guilde `{{guildName}}` ?",
faut le formatter comme aux autres endroits du bot check par exemple les derniers SE

2024-11-26 15:51 UTC, Kyusaor commented on Lib/src/packets/interaction/ReactionCollectorGuildInvite.ts
> +	private readonly inviterKeycloakId: string;
Si, typo indeed

2024-11-26 16:02 UTC, Kyusaor commented on Lang/fr/error.json
> +    "dead": "mort",
C'est supposé aller où du coup?

2024-11-26 16:06 UTC, Kyusaor commented on Lang/fr/error.json
> +    "dead": "mort",
On parle des command requirements? parce que c'est pas sur l'instanciateur de la commande que faut check ici justement

2024-11-26 16:20 UTC, Kyusaor commented on Lang/fr/error.json
> +    "dead": "mort",
En v4 c'est un message d'erreur standard justement, ça appelle la même méthode d'erreur que les autres

2024-11-26 17:23 UTC, romain22222 commented on Lang/fr/error.json
> +    "dead": "mort",
non tu déplaces la raison avec les autres erreurs, ici c'est les raisons réservées à quand tu tentes de faire une commande mais qu'une autre action (shop ouvert, commande rapport en cours, combat en cours etc.) est en cours d'exécution pour le joueur, ce qui n'est pas le cas ici

2024-11-28 22:54 UTC, romain22222 approved these changes

2024-12-02 21:47 UTC, BastLast reviewed
reviewed

2024-12-02 21:48 UTC, merged