Change animal to familier #383
DraftBot-A-Discord-Adventure/DraftBot pull request #384
Opened 2021-04-11 06:30 UTC by Asemerald

2021-04-11 18:01 UTC, BastLast requested changes

2021-04-11 18:01 UTC, BastLast commented on resources/text/commands/shop.json
> +			"success": "{pseudo}, Transaction success!",
c'est fait expres que ca soit pas une majuscule ici, on met pas une maj après une virgule

2021-04-11 18:03 UTC, Asemerald commented on resources/text/commands/shop.json
> +			"success": "{pseudo}, Transaction success!",
Bah, ya vraiment des maj a chaque autre message

2021-04-11 18:04 UTC, Asemerald commented on resources/text/commands/shop.json
> +			"success": "{pseudo}, Transaction success!",
Genre check tout les autre json tu verras

2021-04-11 18:04 UTC, BastLast commented on resources/text/commands/shop.json
> +			"success": "{pseudo}, Transaction success!",
bah faudrait changer tous les autres alors

2021-04-11 18:04 UTC, Asemerald commented on resources/text/commands/shop.json
> +			"success": "{pseudo}, Transaction success!",
bah je fait ça dans cette issue

2021-04-11 18:05 UTC, BastLast commented on resources/text/commands/shop.json
> +			"success": "{pseudo}, Transaction success!",
nan fais le dans une pr à part

2021-04-12 09:48 UTC, Asemerald commented
Bah du coup c'est bon pour les familiers

2021-04-12 09:56 UTC, Asemerald commented
J'avais zappé de push sur une autre branche mdrr, dcp ya le fix des familiers et des majuscules sur la meme pr c'est grave ?

2021-04-12 16:54 UTC, Asemerald commented
C'est bonn @BastLast

2021-04-12 17:11 UTC, BastLast approved these changes

2021-04-12 17:11 UTC, merged