commands refactor
DraftBot-A-Discord-Adventure/DraftBot pull request #470
Opened 2021-06-16 19:13 UTC by eagles666

2021-06-16 19:14 UTC, BastLast commented on src/core/CommandsTest.js
> +			type: "number",
Codacy has a fix for the issue: [Expected indentation of 2 tabs but found 3.](https://app.codacy.com/gh/DraftBot-A-Discord-Adventure/DraftBot/pullRequest?prid=7613090)
```suggestion
		type: "number",
```

2021-06-16 19:14 UTC, BastLast commented on src/core/CommandsTest.js
> +			check: (v) => isAnEmoji(v)
Codacy has a fix for the issue: [Expected indentation of 2 tabs but found 3.](https://app.codacy.com/gh/DraftBot-A-Discord-Adventure/DraftBot/pullRequest?prid=7613090)
```suggestion
		check: (v) => isAnEmoji(v)
```

2021-06-16 19:14 UTC, BastLast commented on src/commands/admin/TestCommand.js
> +const TestCommand = async(language, message, args) => {
Codacy has a fix for the issue: [Missing space before function parentheses.](https://app.codacy.com/gh/DraftBot-A-Discord-Adventure/DraftBot/pullRequest?prid=7613090)
```suggestion
const TestCommand = async (language, message, args) => {
```

2021-06-16 19:14 UTC, BastLast commented on src/core/CommandsTest.js
> +			type: "emoji",
Codacy has a fix for the issue: [Expected indentation of 2 tabs but found 3.](https://app.codacy.com/gh/DraftBot-A-Discord-Adventure/DraftBot/pullRequest?prid=7613090)
```suggestion
		type: "emoji",
```

2021-06-16 19:14 UTC, BastLast commented on src/core/CommandsTest.js
> +			check: (v) => typeof v === typeVariable.INTEGER.type
Codacy has a fix for the issue: [Expected indentation of 2 tabs but found 3.](https://app.codacy.com/gh/DraftBot-A-Discord-Adventure/DraftBot/pullRequest?prid=7613090)
```suggestion
		check: (v) => typeof v === typeVariable.INTEGER.type
```

2021-06-16 19:14 UTC, BastLast commented on src/core/CommandsTest.js
> +		},
Codacy has a fix for the issue: [Expected indentation of 1 tab but found 2.](https://app.codacy.com/gh/DraftBot-A-Discord-Adventure/DraftBot/pullRequest?prid=7613090)
```suggestion
	},
```

2021-06-16 19:17 UTC, BastLast commented
étant donné la taille de la pr je souhaite que @niqore  et @romain22222  fassent une review en plus de la mienne.

Merci x)

2021-06-16 20:26 UTC, romain22222 requested changes

2021-06-16 20:26 UTC, romain22222 commented on src/commands/admin/testCommands/Infos/help.js
> +module.exports.infos = {
a delete, wrong branch

2021-06-16 20:26 UTC, romain22222 commented on src/commands/admin/testCommands/Infos/list.js
> +module.exports.infos = {
a delete, wrong branch

2021-06-16 20:26 UTC, romain22222 commented on src/commands/admin/testCommands/PlayerBased/level.js
> +module.exports.infos = {
a delete, wrong branch

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/BadgeCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/ClassStatsCommand.js
> +
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/DmNotificationCommand.js
> +
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/FightCommand.js
>  	if (await canPerformCommand(message, language, PERMISSION.ROLE.ALL, [EFFECT.BABY, EFFECT.DEAD], attacker) !== true) {
faut delete

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/FriendlyFightCommand.js
> +	aliases: ["ff", "ffight"]
manque la perm user et le niveau requis pour les fights (voire les effets dissallowed, mais le reste est plus important)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/FightCommand.js
> +};
manque le niveau requis pour les fights

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/HelpCommand.js
> +
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/IdeaCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/InviteCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/PingCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/Rarity.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/TopCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/TopServerCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/TopWeekCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/UpdateCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/commands/player/VoteCommand.js
> +};
manque la perm user (voire les effets dissallowed, mais la perm user est plus importante)

2021-06-16 20:26 UTC, romain22222 commented on src/core/CommandsTest.js
> +const fs = require("fs");
à ignorer (par rapport aux tests)

2021-06-16 20:26 UTC, romain22222 commented on src/core/Tools.js
> +/**
à ignorer (par rapport au refact test)

2021-06-19 20:20 UTC, BastLast commented on src/core/CommandsTest.js
> +		},
Codacy has a fix for the issue: [Expected indentation of 1 tab but found 2.](https://app.codacy.com/gh/DraftBot-A-Discord-Adventure/DraftBot/pullRequest?prid=7613090)
```suggestion
	},
```

2021-06-23 20:01 UTC, eagles666 commented
la commande test forcejoinguild semble détruire la guilde 
-> à vérifier si c'est pas quand la personne à pas le niveau requis

2021-06-26 18:59 UTC, BastLast commented on src/commands/player/FriendlyFightCommand.js
> +	aliases: ["ff", "ffight"]
rajouter l'effet mort et baby sur cette commande

2021-06-27 13:23 UTC, Mw3y commented on src/commands/admin/TestCommand.js
>  	if (JsonReader.app.TEST_MODE !== true) {
Le refactor n'est pas très beau.

2021-06-27 13:24 UTC, Mw3y commented on src/commands/admin/TournamentCommand.js
> +global.tournamentChannel = "656586677841821728";
Valeur à mettre dans le fichier de configuration ?

2021-06-27 13:24 UTC, Mw3y commented on src/commands/admin/TournamentCommand.js
> +global.tournamentPower = 500;
Valeur à mettre dans le fichier de configuration ?

2021-06-27 13:31 UTC, Mw3y commented on src/commands/admin/testCommands/Global action/ForcetweTestCommand.js
> +const forcetwe = async () => {
forceTopWeek

2021-06-27 13:32 UTC, Mw3y commented on src/commands/admin/testCommands/Global action/ForcetweTestCommand.js
> +	await DB.twe();
Le nom de la fonction n'est pas assez explicite.

2021-06-27 13:33 UTC, Mw3y commented on src/commands/admin/testCommands/Guild/ForceguildownerTestCommand.js
> +const forceguildowner = async (language, message) => {
forceGuildOwner

2021-06-27 13:33 UTC, Mw3y commented on src/commands/admin/testCommands/Global action/DailytimeoutTestCommand.js
> +const dailytimeout = () => {
dailyTimeout

2021-06-27 13:34 UTC, Mw3y commented on src/commands/admin/testCommands/Fight/AttackTestCommand.js
> +const attack = async (language, message, args) => {
AttackCommand

2021-06-27 13:35 UTC, Mw3y commented on src/commands/admin/testCommands/Fight/DefenseTestCommand.js
> +const defense = async (language, message, args) => {
defenseTestCommand

2021-06-27 13:35 UTC, Mw3y commented on src/commands/admin/testCommands/Fight/FightpointslostTestCommand.js
> +const fightpointslost = async (language, message, args) => {
FightPointLostTestCommand

2021-06-27 13:37 UTC, Mw3y commented on src/commands/admin/testCommands/Guild/ForcejoinguildTestCommand.js
> +const forcejoinguild = async (language, message, args) => {
ForceGuildJoinTestCommand

2021-06-27 13:38 UTC, Mw3y commented on src/commands/admin/testCommands/Guild/GlvlTestCommand.js
> +const glvlTestCommand = async (language, message, args) => {
GuildLevelTestCommand

2021-06-27 13:40 UTC, Mw3y commented on src/commands/admin/testCommands/Guild/GrewardTestCommand.js
> +const greward = async (language, message, args) => {
GuildRewardTestCommand

2021-06-27 13:40 UTC, Mw3y commented on src/commands/admin/testCommands/Guild/GxpTestCommand.js
> +const gxp = async (language, message, args) => {
GuildXpTestCommand

2021-06-27 13:41 UTC, Mw3y commented on src/commands/admin/testCommands/Guild/MygidTestCommand.js
> +const mygid = async (language, message) => {
GuildIdTestCommand

2021-06-27 13:41 UTC, Mw3y commented on src/commands/admin/testCommands/Infos/HelpTestCommand.js
> +const help = async (language, message, args) => {
HelpTestCommand

2021-06-27 13:42 UTC, Mw3y commented on src/commands/admin/testCommands/Infos/ListTestCommand.js
> +const listTestCommand = (language, message) => {
ListTestCommand

2021-06-27 13:42 UTC, Mw3y commented on src/commands/admin/testCommands/Infos/MyidsTestCommand.js
> +const myids = async (language, message) => {
MyIDSTestCommand

2021-06-27 13:43 UTC, Mw3y commented on src/commands/admin/testCommands/Inventory/ArmoridTestCommand.js
> +const armorid = async (language, message, args) => {
ArmorIDTestCommand

2021-06-27 13:43 UTC, Mw3y commented on src/commands/admin/testCommands/Inventory/BackupidTestCommand.js
> +const backupid = async (language, message, args) => {
BackupIDTestCommand

2021-06-27 13:43 UTC, Mw3y commented on src/commands/admin/testCommands/Inventory/ObjectidTestCommand.js
> +const objectid = async (language, message, args) => {
ObjectIDTestCommand

2021-06-27 13:43 UTC, Mw3y commented on src/commands/admin/testCommands/Inventory/PotionidTestCommand.js
> +const potionid = async (language, message, args) => {
PotionIDTestCommand

2021-06-27 13:44 UTC, Mw3y commented on src/commands/admin/testCommands/Inventory/WeaponidTestCommand.js
> +const weaponid = async (language, message, args) => {
WeaponIDTestCommand

2021-06-27 13:44 UTC, Mw3y commented on src/commands/admin/testCommands/Map/ForcereportTestCommand.js
> +const forcereport = async (language, message, args) => {
ForceReportTestCommand

2021-06-27 13:44 UTC, Mw3y commented on src/commands/admin/testCommands/Map/MapinfoTestCommand.js
> +const mapinfo = async (language, message) => {
MapInfosTestCommand

2021-06-27 13:44 UTC, Mw3y commented on src/commands/admin/testCommands/Map/SmallEventTestCommand.js
> +const smallEvent = (language, message, args) => {
SmallEventTestCommand

2021-06-27 13:45 UTC, Mw3y commented on src/commands/admin/testCommands/Map/StoptravelTestCommand.js
> +const stoptravel = async (language, message) => {
StopCurrentTravelTestCommand

2021-06-27 13:45 UTC, Mw3y commented on src/commands/admin/testCommands/Map/TravelTestCommand.js
> +const travel = async (language, message, args) => {
TravelTestCommand

2021-06-27 13:45 UTC, Mw3y commented on src/commands/admin/testCommands/Map/TravelreportTestCommand.js
> +const travelreport = async (language, message) => {
TravelReportTestCommand

2021-06-27 13:45 UTC, Mw3y commented on src/commands/admin/testCommands/Pet/GuildpetTestCommand.js
> +const guildpet = async (language, message, args) => {
GuildPetTestCommand

2021-06-27 13:46 UTC, Mw3y commented on src/commands/admin/testCommands/Pet/PetTestCommand.js
> +const pet = async (language, message, args) => {
PetTestCommand

2021-06-27 13:46 UTC, Mw3y commented on src/commands/admin/testCommands/Pet/PetfreeTestCommand.js
> +const petfree = async (language, message ) => {
PetFreeTestCommand

2021-06-27 13:47 UTC, Mw3y commented on src/commands/admin/testCommands/Pet/PetlpTestCommand.js
> +const petlp = async (language, message, args) => {
PetLovePointsTestCommand

2021-06-27 13:47 UTC, Mw3y commented on src/commands/admin/testCommands/Player/AddmoneyTestCommand.js
> +const addmoney = async (language, message, args) => {
AddMoneyTestCommand

2021-06-27 13:47 UTC, Mw3y commented on src/commands/admin/testCommands/Player/ClearbadgesTestCommand.js
> +const clearbadges = async (language, message) => {
ClearBadgesTestCommand

2021-06-27 13:47 UTC, Mw3y commented on src/commands/admin/testCommands/Player/DestroyTestCommand.js
> +const destroy = async (language, message) => {
DestroyPlayerTestCommand

2021-06-27 13:48 UTC, Mw3y commented on src/commands/admin/testCommands/Player/ExperienceTestCommand.js
> +const experience = async (language, message, args) => {
ExperienceTestCommand

2021-06-27 13:48 UTC, Mw3y commented on src/commands/admin/testCommands/Player/FakevoteTestCommand.js
> +const fakevote = async (language, message) => {
FakeVoteTestCommand

2021-06-27 13:48 UTC, Mw3y commented on src/commands/admin/testCommands/Player/GivebadgeTestCommand.js
> +const givebadgeTestCommand = async (language, message, args) => {
GiveBadgeTestCommand

2021-06-27 13:48 UTC, Mw3y commented on src/commands/admin/testCommands/Player/HealthTestCommand.js
> +const health = async (language, message, args) => {
HealthTestCommand

2021-06-27 13:49 UTC, Mw3y commented on src/commands/admin/testCommands/Player/InitTestCommand.js
> +const init = async (language, message) => {
InitPlayerTestCommand

2021-06-27 13:49 UTC, Mw3y commented on src/commands/admin/testCommands/Player/InitTestCommand.js
> +const init = async (language, message) => {
Peut être ResetOrCreatePlayerTestCommand

2021-06-27 13:49 UTC, Mw3y commented on src/commands/admin/testCommands/Player/LevelTestCommand.js
> +const level = async (language, message, args) => {
PlayerLevelTestCommand

2021-06-27 13:50 UTC, Mw3y commented on src/commands/admin/testCommands/Player/MaxhealthTestCommand.js
> +const maxhealth = async (language, message, args) => {
PlayerMaxHealthTestCommand

2021-06-27 13:50 UTC, Mw3y commented on src/commands/admin/testCommands/Player/MoneyTestCommand.js
> +const money = async (language, message, args) => {
PlayerMoneyTestCommand

2021-06-27 13:50 UTC, Mw3y commented on src/commands/admin/testCommands/Player/ScoreTestCommand.js
> +const score = async (language, message, args) => {
PlayerScoreTestCommand

2021-06-27 13:51 UTC, Mw3y commented on src/commands/admin/testCommands/Player/SuicideTestCommand.js
> +const suicide = async (language, message) => {
PlayerSuicideTestCommand

2021-06-27 13:51 UTC, Mw3y commented on src/commands/admin/testCommands/Player/WeeklyscoreTestCommand.js
> +const weeklyscore = async (language, message, args) => {
PlayerWeeklyScoreTestCommand

2021-06-27 13:51 UTC, Mw3y commented on src/commands/admin/testCommands/Time/AdailyTestCommand.js
> +async function adaily(language, message, args) {
AdvancePlayerDailyTestCommand

2021-06-27 13:52 UTC, Mw3y commented on src/commands/admin/testCommands/Time/AgdTestCommand.js
> +async function agd(language, message, args) {
AdvanceGuildDailyTestCommand

2021-06-27 13:52 UTC, Mw3y commented on src/commands/admin/testCommands/Time/ApfreeTestCommand.js
> +async function apfree(language, message, args) {
AdvancePetFreeTestCommand

2021-06-27 13:54 UTC, Mw3y commented on src/commands/admin/testCommands/Time/AtravelTestCommand.js
> + * Quick travel your travel of a given time
REVOIR **TOUTES** LES DESCRIPTIONS DES COMMANDES DANS LE DOSSIER "TIME"

2021-06-27 13:54 UTC, Mw3y commented on src/commands/admin/testCommands/Time/AtravelTestCommand.js
> +async function atravel(language, message, args) {
Je ne sais même pas quoi mettre.

2021-06-27 13:54 UTC, Mw3y commented on src/commands/admin/testCommands/Time/BlockTestCommand.js
> +async function block(language, message, args) {
BlockPlayerTestCommand

2021-06-27 13:54 UTC, Mw3y commented on src/commands/admin/testCommands/Time/EffectTestCommand.js
> +async function effect(language, message, args) {
PlayerEffectTestCommand

2021-06-27 13:55 UTC, Mw3y commented on src/commands/admin/testCommands/Time/JailTestCommand.js
> +async function effect(language, message, args) {
JailPlayerTestCommand

2021-06-27 13:55 UTC, Mw3y commented on src/commands/admin/testCommands/Time/RmeffectTestCommand.js
> +async function rmeffect(language, message) {
RemovePlayerEffectTestCommand

2021-06-27 13:55 UTC, Mw3y commented on src/commands/admin/testCommands/Time/TopggatimeTestCommand.js
> +async function topggatime(language, message, args) {
ResetTopGGVoteTimeTestCommand

2021-06-27 13:56 UTC, Mw3y commented on src/commands/admin/testCommands/Time/TopggatimeTestCommand.js
> +	entity.Player.topggVoteAt -= parseInt(args[0]) * 60000;
entity.Player.topggVoteAt = 0; ??

2021-06-27 13:58 UTC, Mw3y commented on src/commands/guild/GuildCommand.js
>   * @param {("fr"|"en")} language - Language to use in the response
Inversion des arguments de la fonction mais pas dans le block de commentaire

2021-06-27 13:58 UTC, Mw3y commented on src/commands/guild/GuildCreateCommand.js
> +const GuildCreateCommand = async (message, language, args) => {
Inversion des arguments de la fonction mais pas dans le block de commentaire

2021-06-27 13:59 UTC, Mw3y commented on src/commands/guild/GuildDailyCommand.js
> +const GuildDailyCommand = async (message, language, args, forcedReward) => {
Inversion des arguments de la fonction mais pas dans le block de commentaire

2021-06-27 13:59 UTC, Mw3y commented on src/commands/guild/GuildDescriptionCommand.js
> +const GuildDescriptionCommand = async (message, language, args) => {
Inversion des arguments de la fonction mais pas dans le block de commentaire

2021-06-27 13:59 UTC, Mw3y commented on src/commands/guild/GuildElderCommand.js
>  	let elderGuild;
let elderEntity, guild, elderGuild;

2021-06-27 14:01 UTC, Mw3y commented on src/commands/pets/MyPetCommand.js
> +const MyPetCommand = async (message, language, args) => {
elderEntity;
	let guild;
	let elderGuild;

2021-06-27 14:02 UTC, Mw3y commented on src/commands/pets/MyPetCommand.js
> +const MyPetCommand = async (message, language, args) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:02 UTC, Mw3y commented on src/commands/pets/PetFeedCommand.js
> +const PetFeedCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:02 UTC, Mw3y commented on src/commands/pets/PetFreeCommand.js
> +const PetFreeCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:02 UTC, Mw3y commented on src/commands/pets/PetNicknameCommand.js
> +const PetNicknameCommand = async (message, language, args) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:04 UTC, Mw3y commented on src/commands/pets/MyPetCommand.js
>  	if (entity === null) {
!entity

2021-06-27 14:04 UTC, Mw3y commented on src/commands/pets/PetSellCommand.js
> +const PetSellCommand = async (message, language, args) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:05 UTC, Mw3y commented on src/commands/pets/PetTradeCommand.js
> +const PetTradeCommand = async function(message, language) {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:05 UTC, Mw3y commented on src/commands/pets/PetTransferCommand.js
> +const PetTransferCommand = async function(message, language, args) {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:05 UTC, Mw3y commented on src/commands/player/ClassCommand.js
> +const ClassCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:06 UTC, Mw3y commented on src/commands/player/ClassStatsCommand.js
> +async function ClassStatsCommand(message, language) {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:06 UTC, Mw3y commented on src/commands/player/DailyCommand.js
> +const DailyCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:06 UTC, Mw3y commented on src/commands/player/DmNotificationCommand.js
> +const DmnotificationCommand = async (message, language) => {
DMNotificationCommand

2021-06-27 14:06 UTC, Mw3y commented on src/commands/player/DmNotificationCommand.js
> +const DmnotificationCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:06 UTC, Mw3y commented on src/commands/player/DrinkCommand.js
> +const DrinkCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:06 UTC, Mw3y commented on src/commands/player/FightCommand.js
> +const FightCommand = async function(message, language, args, friendly = false) {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:07 UTC, Mw3y commented on src/commands/player/HelpCommand.js
> +	if (!args.length) {
if(!args) {} ??

2021-06-27 14:07 UTC, Mw3y commented on src/commands/player/IdeaCommand.js
> +const IdeaCommand = (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:28 UTC, Mw3y commented on src/commands/player/InventoryCommand.js
> +const InventoryCommand = async (message, language, args) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:29 UTC, Mw3y commented on src/commands/player/InventoryCommand.js
>  	if (entity === null) {
!entity

2021-06-27 14:29 UTC, Mw3y commented on src/commands/player/InviteCommand.js
> +const InviteCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:29 UTC, Mw3y commented on src/commands/player/MapCommand.js
> +const MapCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:30 UTC, Mw3y commented on src/commands/player/MapCommand.js
>  	log("Player " + message.author + " asked the map");
asked **for** the map

2021-06-27 14:30 UTC, Mw3y commented on src/commands/player/PingCommand.js
> +const PingCommand = (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:30 UTC, Mw3y commented on src/commands/player/ProfileCommand.js
>  	if (entity === null) {
!entity

2021-06-27 14:31 UTC, Mw3y commented on src/commands/player/RarityCommand.js
> +const RarityCommand = (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:31 UTC, Mw3y commented on src/commands/player/RespawnCommand.js
> +const RespawnCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:31 UTC, Mw3y commented on src/commands/player/SellCommand.js
> +const SellCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:31 UTC, Mw3y commented on src/commands/player/ShopCommand.js
> +const ShopCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:32 UTC, Mw3y commented on src/commands/player/SwitchCommand.js
> +const SwitchCommand = async (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:33 UTC, Mw3y commented on src/commands/player/TopServerCommand.js
> +	return message.channel.send(":x: This command is broken due to changes in the discord API, We hope to get it back online soon!");
À mettre dans les fichiers de traduction.

2021-06-27 14:34 UTC, Mw3y commented on src/commands/player/UnlockCommand.js
> +const UnlockCommand = async (message, language, args) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:34 UTC, Mw3y commented on src/commands/player/UnlockCommand.js
>  	if (lockedEntity === null) {
!lockedEntity

2021-06-27 14:34 UTC, Mw3y commented on src/commands/player/UpdateCommand.js
> +const UpdateCommand = (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:34 UTC, Mw3y commented on src/commands/player/VoteCommand.js
> +const VoteCommand = (message, language) => {
Inversion des arguments mais pas dans le block commentaire.

2021-06-27 14:36 UTC, Mw3y commented on src/core/Command.js
>  	.getAliasesFromCommand = Command.getAliasesFromCommand;
Formatage à refaire.

2021-06-27 14:40 UTC, Mw3y commented on src/core/Tools.js
> +};
```suggestion
global.getIdFromMention = (variable) => typeof variable === "string" ? variable.slice(3,variable.length - 1) : "";
```

2021-06-27 14:41 UTC, Mw3y commented on src/core/Tools.js
> +};
```suggestion
global.isAMention = (variable) => typeof variable === "string" ? RegExp(/^<@!?[0-9]{18}>$/).test(variable) : false;
```

2021-06-27 14:43 UTC, Mw3y requested changes
Modifications à effectuer.

2021-06-27 14:54 UTC, romain22222 commented on src/commands/admin/TestCommand.js
>  	if (JsonReader.app.TEST_MODE !== true) {
qu'entends tu par la ?

est ce que j'enlève les commentaires ?

2021-06-27 14:55 UTC, BastLast commented on src/commands/admin/TestCommand.js
>  	if (JsonReader.app.TEST_MODE !== true) {
nan c'est le == true pour tester un boolean ...

2021-06-27 14:57 UTC, Mw3y commented on src/commands/admin/TestCommand.js
>  	if (JsonReader.app.TEST_MODE !== true) {
En gros le code a besoin d'une sérieuse amélioration car il n'est pas assez structuré et organisé.

2021-06-27 15:18 UTC, romain22222 commented on src/commands/admin/testCommands/Infos/ListTestCommand.js
> +const listTestCommand = (language, message) => {
par contre dans eslint, si c'est une fonction, la règle c'est camelCase, donc tout collé, et majuscules à chaque mot, sauf le premier, donc ici, c'est good

2021-06-27 15:52 UTC, eagles666 commented on src/commands/guild/GuildElderCommand.js
>  	let elderGuild;
@BastLast quel style ici ?

2021-06-27 15:53 UTC, BastLast commented on src/commands/guild/GuildElderCommand.js
>  	let elderGuild;
@niqore help xD

2021-06-27 16:00 UTC, romain22222 commented on src/commands/admin/TestCommand.js
>  	if (JsonReader.app.TEST_MODE !== true) {
qu'entends tu par la ?

2021-06-27 16:03 UTC, romain22222 commented on src/core/Tools.js
> +};
après analyse de codefactor, l'ancien code est mieux, pour les deux...

2021-06-27 16:09 UTC, eagles666 commented on src/commands/player/TopServerCommand.js
> +	return message.channel.send(":x: This command is broken due to changes in the discord API, We hope to get it back online soon!");
vraiment nécessaire ? vu que c'est temporaire ?

2021-06-27 16:10 UTC, BastLast commented on src/commands/player/TopServerCommand.js
> +	return message.channel.send(":x: This command is broken due to changes in the discord API, We hope to get it back online soon!");
non osef x)

2021-06-27 16:14 UTC, romain22222 commented on src/core/Command.js
Fonction trop complexe, faut faire du extract method, car codefactor gueule

2021-06-27 16:21 UTC, eagles666 commented on src/commands/admin/TournamentCommand.js
> +global.tournamentChannel = "656586677841821728";
@BastLast je le fait ? parce que faut remplacer les deux variables globales par le JsonReader

2021-06-27 16:23 UTC, BastLast commented on src/commands/admin/TournamentCommand.js
> +global.tournamentChannel = "656586677841821728";
oui fais le, pense à mettre à jour le fichier de config défault

2021-06-27 16:32 UTC, eagles666 commented
je rajoute ca ici mais les commandes test ne sont pas des commandes admin donc pourquoi elles sont dans le dossier admin ?

2021-06-27 16:40 UTC, eagles666 commented on src/commands/admin/TournamentCommand.js
> +global.tournamentChannel = "656586677841821728";
en faisant ça la commande tournament aurait plus d'intéret vu qu'elle permettait de modifier les valeurs à la volée

2021-06-27 20:36 UTC, Mw3y commented on src/commands/admin/TestCommand.js
> +		const testCommand = args[0] ?? "list";
Attention, peut ne pas fonctionner avec une version de nodejs trop vieille.

2021-06-27 20:36 UTC, Mw3y commented on src/commands/admin/TestCommand.js
> +		const argsTest = args.slice(1) ?? [];
Attention, peut ne pas fonctionner avec une version de nodejs trop vieille.

2021-06-28 10:33 UTC, Mw3y commented on src/commands/admin/TestCommand.js
> +		await CT.executeAndAlertUser(language, message, commandTestCurrent, argsTest);
```suggestion
if (commandTestCurrent) {
    // Third, we check if the test command has the good arguments
    const testGoodFormat = CT.isGoodFormat(commandTestCurrent, argsTest, message);
    // Last, we execute the test command
    if (testGoodFormat[0]) {
        await CT.executeAndAlertUser(language, message, commandTestCurrent, argsTest);
    } else {
        message.channel.send(testGoodFormat[1])
    }
}
```

2021-06-28 14:06 UTC, romain22222 approved these changes

2021-07-01 20:08 UTC, BastLast commented on src/commands/admin/TestCommand.js
> +		const testCommand = args[0] ?? "list";
osef on a bump la v mini à la v 14 lts

2021-07-01 20:10 UTC, BastLast commented on src/core/Command.js
>  	.getAliasesFromCommand = Command.getAliasesFromCommand;
possible d'avoir plus de détails @Mw3y  ?

2021-07-01 20:13 UTC, BastLast commented on src/commands/admin/TournamentCommand.js
> +global.tournamentChannel = "656586677841821728";
on règle ca dans une issue à part

2021-07-01 20:38 UTC, Mw3y approved these changes

2021-07-01 20:40 UTC, merged