Dure variable
DraftBot-A-Discord-Adventure/DraftBot pull request #511
Opened 2021-07-31 23:36 UTC by BastLast

2021-07-31 23:45 UTC, BastLast commented
[CodeFactor](https://www.codefactor.io/repository/github/draftbot-a-discord-adventure/draftbot) found an issue: Unreachable code.

It's currently on:
[src\commands\admin\testCommands\Map\TravelTestCommand.js:28](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/5f6cbf5d770005c01db739d86851c8ec1ec8d4af/src/commands/admin/testCommands/Map/TravelTestCommand.js#L28)
Commit 5f6cbf5d770005c01db739d86851c8ec1ec8d4af

2021-07-31 23:45 UTC, BastLast commented
> [CodeFactor](https://www.codefactor.io/repository/github/draftbot-a-discord-adventure/draftbot) found an issue: Unreachable code.
> 
> It's currently on:
> [src\commands\admin\testCommands\Map\TravelTestCommand.js:28](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/5f6cbf5d770005c01db739d86851c8ec1ec8d4af/src/commands/admin/testCommands/Map/TravelTestCommand.js#L28)
> Commit [5f6cbf5](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/commit/5f6cbf5d770005c01db739d86851c8ec1ec8d4af)

@romain22222  tu pourras t'en occuper à l'ocaz ? ( pas urgent je sais que tu es en vacance no soucis )

2021-08-04 23:06 UTC, BastLast commented
Penser à clarifier points gagnés. (TODO)

2021-08-05 00:00 UTC, romain22222 requested changes

2021-08-05 14:01 UTC, romain22222 approved these changes

2021-08-05 14:01 UTC, romain22222 commented on src/core/smallEvents/botFactsSmallEvent.js
> +	const outReceived = "nbPlayersOnYourMap";
```suggestion
	const outReceived = draftbotRandom.pick(Object.keys(translationBF.possiblesInfos));
```

2021-08-05 14:31 UTC, merged