Inventory extension
DraftBot-A-Discord-Adventure/DraftBot pull request #563
Opened 2021-09-08 16:39 UTC by niqore

2021-09-08 19:29 UTC, romain22222 requested changes

2021-09-08 19:29 UTC, romain22222 commented on src/commands/admin/testCommands/Player/InitPlayerTestCommand.js
> +	await InventoryInfo.create({
je vois que tu crées l'inventaire, puis que tu lui passes les valeurs par défaut. est ce que l'on peut pas directement mettre par défaut dans la table des slots l'id 0 pour un item ?

2021-09-08 19:29 UTC, romain22222 commented on src/commands/player/ProfileCommand.js
> -				cumulativeDefense: await entity.getCumulativeDefense(await entity.Player.Inventory.getWeapon(),
manque un ptit retour à la ligne ici

2021-09-08 19:29 UTC, romain22222 commented on src/core/smallEvents/interactOtherPlayersSmallEvent.js
> -	}
du coup, vous avez choisi d'enlever la dupli de potion ?

2021-09-08 20:35 UTC, niqore commented on src/commands/admin/testCommands/Player/InitPlayerTestCommand.js
> +	await InventoryInfo.create({
Merci tu viens de me faire trouver un bug

2021-09-08 21:11 UTC, niqore commented on src/commands/player/ProfileCommand.js
> -				cumulativeDefense: await entity.getCumulativeDefense(await entity.Player.Inventory.getWeapon(),
C'est du code supprimé ça

2021-09-08 21:12 UTC, niqore commented on src/core/smallEvents/interactOtherPlayersSmallEvent.js
> -	}
Oui c'était plus simple et avec le nouvel inventaire ça aurait été trop cheat car c'est facile d'avoir des slots de libre

2021-09-08 21:16 UTC, romain22222 approved these changes

2021-09-20 11:24 UTC, niqore commented
Impossible de rebase donc je merge

2021-09-20 11:24 UTC, merged