fix nerf display #787, top display #793 & object 11 emoji
DraftBot-A-Discord-Adventure/DraftBot pull request #819
Opened 2021-12-28 13:50 UTC by Pietagorh

2022-01-05 15:59 UTC, Pietagorh commented
En fait vu que j'ai fait plein de trucs j'vais tous les mettre ici x)
Pas envie de faire 10928029 pr

2022-01-06 14:51 UTC, BastLast commented
ya un tag de l'issue #787  je pense que c'est une erreur ?

2022-01-06 14:53 UTC, BastLast requested changes
Ce code ne fait aucun sens, go revert ça mdr
La lecture de l'url n'est pas asynchrone donc aucun intérêt de l'await. Ça ne change pas le comportement du truc

2022-01-06 15:55 UTC, Pietagorh commented
> Ce code ne fait aucun sens, go revert ça mdr
> La lecture de l'url n'est pas asynchrone donc aucun intérêt de l'await. Ça ne change pas le comportement du truc

Ouais j'y ai pensé en cours mais pas eu le temps de modif x)

2022-01-06 15:55 UTC, Pietagorh commented
> ya un tag de l'issue #787  je pense que c'est une erreur ?

Oui x)

2022-01-06 15:57 UTC, Pietagorh commented
Du coup je re commit ou juste on laisse comme ça ?

2022-01-06 18:15 UTC, Pietagorh commented
> Ce code ne fait aucun sens, go revert ça mdr La lecture de l'url n'est pas asynchrone donc aucun intérêt de l'await. Ça ne change pas le comportement du truc

Done

2022-01-07 17:37 UTC, BastLast approved these changes

2022-01-07 17:37 UTC, merged