Typos récentes
DraftBot-A-Discord-Adventure/DraftBot pull request #904
Opened 2022-02-16 21:45 UTC by Thesmokingllama

2022-02-17 12:42 UTC, BastLast requested changes

2022-02-17 12:53 UTC, BastLast commented
btw @Thesmokingllama  ca serait bien de mettre à jour ton fork et de pas partir de n'importe ou parce que là c'est une catastrophe l'historique git ;(

2022-02-19 14:04 UTC, romain22222 requested changes

2022-02-19 14:04 UTC, romain22222 commented on resources/text/smallEvents/lottery.json
> +				"money": " Vous avez {negativeMoney?perdu:gagné} **{money} :{negativeMoney?money_with_wings:moneybag}:** !",
pourquoi ce changement ?

2022-02-19 14:04 UTC, romain22222 commented on resources/text/smallEvents/space.json
> +				"un homme surgi de nulle part court vers vous et se présente sous le nom de **{name}**",
c'est bien surgit ici (voir conjugaison surgir présent -> https://la-conjugaison.nouvelobs.com/du/verbe/surgir.php)

2022-02-21 07:14 UTC, BastLast commented
je close cette pr on la refait au propre ce soir :)

2022-02-21 07:14 UTC, closed without merging

2022-02-22 18:45 UTC, Thesmokingllama commented on resources/text/commands/help.json
> +					"description": "Les badges sont des distinctions difficiles à obtenir qui ont été créées pour récompenser les personnes ayant le plus soutenu le développement du bot. La liste des badges est dis
j'ai check et non c'est distinction le sujet de créées, on est dans une PSR

2022-02-22 18:49 UTC, Thesmokingllama commented on resources/text/events/25.json
> +						"fr": "En pillant les corps, vous vous faites attraper brusquement par un soldat. Celui-ci profite de vootre situation pour vous détrousser avant de vous sommer de continuer votre route rapidem
oulah oui, je modifie ça x)
Quel est le problème avec la seconde partie ? sommer est synonyme d'ordonner

2022-02-22 19:07 UTC, BastLast commented on resources/text/commands/help.json
> +					"description": "Les badges sont des distinctions difficiles à obtenir qui ont été créées pour récompenser les personnes ayant le plus soutenu le développement du bot. La liste des badges est dis
soit

2022-02-22 19:32 UTC, Pietagorh commented on resources/text/events/29.json
> +						"fr": "👀 Vous restez à votre place, en plein soleil pendant une quinzaine de minutes, puis vous écroulez.",
Non, c'est un début qu'on a déjà eu, et c'est bon (approuvé par Hito, Pourfi et moi x))
Le "vous" qui est enlevé c'est le sujet, pas le COD, pour éviter la répétition

2022-02-22 19:33 UTC, Pietagorh commented on resources/text/events/42.json
> +						"fr": "Elle vous indique une taverne à quelques kilomètres. Vous vous y rendez, vous remplissez l’estomac et vous reposez. Après avoir réglé l’addition vous reprenez votre marche.",
Non

2022-02-22 19:34 UTC, Pietagorh commented on resources/text/smallEvents/lottery.json
> +				"money": " Vous avez {negativeMoney?perdu:gagné} **{money} :{negativeMoney?money_with_wings:moneybag}:** !",
On met le gras sur la récompense, pas sur la ponctuation x)

2022-02-22 19:34 UTC, BastLast commented on resources/text/events/48.json
> +		"fr": "🏯 Vous êtes à la recherche d'un artéfact. Vous le convoitez car celui-ci, d'après les légendes, offrirait richesse et pouvoir à son possesseur. Après que votre quête vous a mené jusque devan
Absolument pas un problème dans cette phrase imo

2022-02-22 19:35 UTC, Pietagorh commented on resources/text/events/48.json
> +		"fr": "🏯 Vous êtes à la recherche d'un artéfact. Vous le convoitez car celui-ci, d'après les légendes, offrirait richesse et pouvoir à son possesseur. Après que votre quête vous a mené jusque devan
"jusqu'au devant d'une tour" serait plus joli je trouve mais celle actuelle marche 🤔

2022-02-22 19:59 UTC, Thesmokingllama commented on resources/text/events/29.json
> +						"fr": "👀 Vous restez à votre place, en plein soleil pendant une quinzaine de minutes, puis vous écroulez.",
bah non, y a le "Vous" du début qui fait le taff -> "Vous [...] puis vous écroulez"

2022-02-22 20:04 UTC, Thesmokingllama commented on resources/text/events/42.json
> +						"fr": "Elle vous indique une taverne à quelques kilomètres. Vous vous y rendez, vous remplissez l’estomac et vous reposez. Après avoir réglé l’addition vous reprenez votre marche.",
je vois pas de quelle virgule tu parles mais je pense qu'une réécriture complète est nécessaire de toute manière, il y a mieux à faire qu'une énumération des actions du joueur, là c'est une correction directe et fidèle au texte original pas ouf que je proposais.

2022-02-22 20:09 UTC, Thesmokingllama commented on resources/text/events/48.json
> +		"fr": "🏯 Vous êtes à la recherche d'un artéfact. Vous le convoitez car celui-ci, d'après les légendes, offrirait richesse et pouvoir à son possesseur. Après que votre quête vous a mené jusque devan
« Jusque » s’écrit tel quel lorsqu’il est suivi d’une préposition commençant par une consonne, comme « dans », « chez », « vers »…
Ici, on a "devant" qui est une préposition donc ça fonctionne

2022-02-22 20:09 UTC, Pietagorh commented on resources/text/events/42.json
> +						"fr": "Elle vous indique une taverne à quelques kilomètres. Vous vous y rendez, vous remplissez l’estomac et vous reposez. Après avoir réglé l’addition vous reprenez votre marche.",
Celle après "rendez"

2022-02-22 20:13 UTC, Thesmokingllama commented on resources/text/events/42.json
> +						"fr": "Elle vous indique une taverne à quelques kilomètres. Vous vous y rendez, vous remplissez l’estomac et vous reposez. Après avoir réglé l’addition vous reprenez votre marche.",
ah bah si elle est justifiée du coup, comme c'est une énumération chaque action (représentée par un verbe mais je vous fais pas de dessin) est séparée par une virgule. Selon moi, tout va bien niveau syntaxe.

2022-02-22 20:24 UTC, Thesmokingllama commented on resources/text/smallEvents/space.json
> +				"un homme surgi de nulle part court vers vous et se présente sous le nom de **{name}**",
les deux passent : 
 - Sur la version originale c'est bien un verbe au présent mais il aurait fallu ajouter une virgule après "nulle part" pour séparer les propositions. 
 - Dans la nouvelle version "surgi" n'est pas un verbe (nahméo je sais conjuguer surgir au présent), il change de fonction pour devenir un épithète (remplace par "arrivé" pour mieux comprendre il m'a fallu du temps aussi)